# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:49:18+00:00



import argparse
import json
import os
from typing import *
from typing import Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import UploadFile

from models import (
    DecodeStringPostRequest,
    InputCalculateMinMax,
    InputCalculateNumber,
    InputCalculateNumbers,
    InputCalculatePower,
    InputCalculateSeries,
    InputCaseConversion,
    InputCollectionConversion,
    InputCollectionConversionXML,
    InputCollectionCount,
    InputCollectionFilter,
    InputCollectionModify,
    InputCollectionReplace,
    InputCollectionSearch,
    InputCollectionSearchNumeric,
    InputCollectionSort,
    InputCollectionSplit,
    InputConvertAngle,
    InputConvertArea,
    InputConvertDistance,
    InputConvertDuration,
    InputConvertEnergy,
    InputConvertPower,
    InputConvertSpeed,
    InputConvertTemperature,
    InputConvertVolume,
    InputConvertWeight,
    InputCsvConversionJSON,
    InputCurrencyConversion,
    InputCurrencyFormat,
    InputDataQuery,
    InputDateTimeConversion,
    InputDateTimeDifference,
    InputDateTimeFormat,
    InputDateTimeInfo,
    InputGenerateHash,
    InputGenerateUniqueID,
    InputJoinStrings,
    InputJsonConversionCSV,
    InputJsonConversionHTML,
    InputJsonConversionXML,
    InputMarketIndex,
    InputNumberRange,
    InputQRCode,
    InputRedactString,
    InputReplaceString,
    InputSplitString,
    InputStockPrices,
    InputString,
    InputStringComparison,
    InputStringContains,
    InputStringToFile,
    InputTextToSpeech,
    InputTranslateString,
    InputTrimString,
    InputVerifyHash,
    InputXmlConversionJSON,
    OutputBoolean,
    OutputCollectionNumber,
    OutputCollectionResult,
    OutputCollectionString,
    OutputDateDifference,
    OutputDateInfo,
    OutputMarketIndex,
    OutputMultiCollection,
    OutputNumber,
    OutputStockPrice,
    OutputString,
    OutputStringArray,
    ShortenLinkPostRequest,
    URLDecodePostRequest,
    ValidateEmailPostRequest,
)

app = MCPProxy(
    contact={
        'email': 'support@apptigent.com',
        'name': 'Customer Support',
        'url': 'https://www.apptigent.com/help/',
    },
    description="Apptigent PowerTools Developer Edition is a powerful suite of API endpoints for custom applications running on any stack. Manipulate text, modify collections, format dates and times, convert currency, perform advanced mathematical calculations, shorten URL's, encode strings, convert text to speech, translate content into multiple languages, process images, and more. PowerTools is the ultimate developer toolkit.",
    title='PowerTools Developer',
    version='2021.1.01',
    servers=[{'url': 'https://connect.apptigent.com/api/utilities'}],
)


@app.post(
    '/AddToCollection',
    description=""" Add an item to a collection """,
    tags=['collection_manipulation', 'collection_management_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def add_to_collection(body: InputCollectionModify = None):
    """
    Collections - Add to collection
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CSVtoJSON',
    description=""" Convert a CSV string to a JSON array """,
    tags=['data_format_conversion', 'collection_manipulation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def csv_to_json(body: InputCsvConversionJSON = None):
    """
    Data - CSV to JSON
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateAbsolute',
    description=""" Calculate the absolute value of a number """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_absolute(body: InputCalculateNumber = None):
    """
    Math - Calculate Absolute
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateAddition',
    description=""" Calculate the sum of two numbers """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_addition(body: InputCalculateNumbers = None):
    """
    Math - Calculate Addition
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateAverage',
    description=""" Calculate the average of two or more numbers """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_average(body: InputCalculateSeries = None):
    """
    Math - Calculate average
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateCosine',
    description=""" Calculate the cosine value of an angle """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_cosine(body: InputCalculateNumber = None):
    """
    Math - Calculate Cosine
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateDivision',
    description=""" Calculate the quotient of two numbers """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_division(body: InputCalculateNumbers = None):
    """
    Math - Calculate Division
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateLogarithm',
    description=""" Calculate the logarithm of a number """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_logarithm(body: InputCalculateNumber = None):
    """
    Math - Calculate Logarithm
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateMedian',
    description=""" Calculate the median of two or more numbers """,
    tags=['math_operations', 'collection_management_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_median(body: InputCalculateSeries = None):
    """
    Math - Calculate median
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateMinMax',
    description=""" Calculate the minimum or maximum value in a sequence of numbers """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_min_max(body: InputCalculateMinMax = None):
    """
    Math - Calculate minimum or maximum
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateModulo',
    description=""" Calculate the remainder of dividing two numbers """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_modulo(body: InputCalculateNumbers = None):
    """
    Math - Calculate Modulo
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateMultiplication',
    description=""" Calculate the product of two numbers """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_multiplication(body: InputCalculateNumbers = None):
    """
    Math - Calculate Multiplication
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateNthRoot',
    description=""" Calculate the n-th root of a number """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_nth_root(body: InputCalculateNumbers = None):
    """
    Math - Calculate Nth Root
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculatePower',
    description=""" Raise number to a specified power """,
    tags=['math_operations', 'unit_conversion'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_power(body: InputCalculatePower = None):
    """
    Math - Calculate power
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateSine',
    description=""" Calculate the sine value of an angle """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_sine(body: InputCalculateNumber = None):
    """
    Math - Calculate Sine
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateSquareRoot',
    description=""" Calculate the square root of a number """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_square_root(body: InputCalculateNumber = None):
    """
    Math - Calculate Square Root
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateSubtraction',
    description=""" Calculate the difference between two numbers """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_subtraction(body: InputCalculateNumbers = None):
    """
    Math - Calculate Subtraction
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateSum',
    description=""" Calculate the sum of two or more numbers """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_sum(body: InputCalculateSeries = None):
    """
    Math - Calculate sum
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateTangent',
    description=""" Calculate the tangent value of an angle """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_tangent(body: InputCalculateNumber = None):
    """
    Math - Calculate Tangent
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CalculateVariance',
    description=""" Calculate the statistical variance of two or more numbers """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def calculate_variance(body: InputCalculateSeries = None):
    """
    Math - Calculate variance
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CollectionContainsNumber',
    description=""" Determine if a collection contains a specific number """,
    tags=['collection_manipulation', 'collection_management_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def collection_contains_number(body: InputCollectionSearchNumeric = None):
    """
    Collections - Contains number
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CollectionContainsString',
    description=""" Determine if any items in a collection contain a specific string """,
    tags=['collection_manipulation', 'collection_management_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def collection_contains_string(body: InputCollectionSearch = None):
    """
    Collections - Contains string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CollectionEndsWithString',
    description=""" Determine if any items in a collection end with a specific string """,
    tags=[
        'collection_manipulation',
        'collection_management_operations',
        'string_operations',
    ],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def collection_ends_with_string(body: InputCollectionSearch = None):
    """
    Collections - Ends with string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CollectionStartsWithString',
    description=""" Determine if any items in a collection start with a specific string """,
    tags=[
        'collection_manipulation',
        'collection_management_operations',
        'string_operations',
    ],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def collection_starts_with_string(body: InputCollectionSearch = None):
    """
    Collections - Starts with string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CollectionToJSON',
    description=""" Convert a collection to a named JSON object """,
    tags=['collection_manipulation', 'data_format_conversion'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def collection_to_j_s_o_n(body: InputCollectionConversion = None):
    """
    Collections - Collection to JSON
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CollectionToXML',
    description=""" Convert a collection to an XML string """,
    tags=['collection_manipulation', 'data_format_conversion'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def collection_to_xml(body: InputCollectionConversionXML = None):
    """
    Collections - Collection to XML
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CompareStrings',
    description=""" Perform a comparison of two strings """,
    tags=['string_operations', 'text_transformation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def compare_strings(body: InputStringComparison = None):
    """
    Text - Compare strings
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ContainsString',
    description=""" Determine if a string contains another string """,
    tags=['text_transformation', 'string_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def contains_string(body: InputStringContains = None):
    """
    Text - Contains string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertAngle',
    description=""" Convert value from one angle measurement to another """,
    tags=['math_operations', 'unit_conversion'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_angle(body: InputConvertAngle = None):
    """
    Math - Convert angle
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertArea',
    description=""" Convert value from one area measurement to another """,
    tags=['unit_conversion'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_area(body: InputConvertArea = None):
    """
    Math - Convert area
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertCase',
    description=""" Convert string to upper, lower or title case """,
    tags=['text_transformation', 'string_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_case(body: InputCaseConversion = None):
    """
    Text - Convert case
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertCurrency',
    description=""" Calculate monetary value in a different currency """,
    tags=['currency_exchange_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_currency(body: InputCurrencyConversion = None):
    """
    Currency - Convert currency
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertDistance',
    description=""" Convert value from one distance measurement to another """,
    tags=['unit_conversion', 'math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_distance(body: InputConvertDistance = None):
    """
    Math - Convert distance
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertDuration',
    description=""" Convert value from one duration measurement to another """,
    tags=['unit_conversion', 'date_time_utilities'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_duration(body: InputConvertDuration = None):
    """
    Math - Convert duration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertEnergy',
    description=""" Convert value from one energy measurement to another """,
    tags=['unit_conversion', 'math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_energy(body: InputConvertEnergy = None):
    """
    Math - Convert energy
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertImage',
    description=""" Convert an image from one format to another """,
    tags=['image_file_processing', 'advanced_image_handling'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_image(file: UploadFile):
    """
    Files - Convert Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertPower',
    description=""" Convert value from one power measurement to another """,
    tags=['math_operations', 'unit_conversion'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_power(body: InputConvertPower = None):
    """
    Math - Convert power
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertSpeed',
    description=""" Convert value from one speed measurement to another """,
    tags=['unit_conversion'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_speed(body: InputConvertSpeed = None):
    """
    Math - Convert speed
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertTemperature',
    description=""" Convert value from one temperature measurement to another """,
    tags=['unit_conversion'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_temperature(body: InputConvertTemperature = None):
    """
    Math - Convert temperature
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertVolume',
    description=""" Convert value from one volume measurement to another """,
    tags=['unit_conversion', 'math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_volume(body: InputConvertVolume = None):
    """
    Math - Convert volume
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ConvertWeight',
    description=""" Convert value from one weight measurement to another """,
    tags=['unit_conversion', 'math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def convert_weight(body: InputConvertWeight = None):
    """
    Math - Convert weight
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CountCollection',
    description=""" Count a collection of items """,
    tags=['collection_manipulation', 'collection_management_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def count_collection(body: InputCollectionCount = None):
    """
    Collections - Count collection
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/CropImage',
    description=""" Crop an image """,
    tags=['image_file_processing', 'advanced_image_handling'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def crop_image(file: UploadFile):
    """
    Files - Crop Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/DateTimeDifference',
    description=""" Calculate the difference between two dates """,
    tags=['date_time_utilities', 'datetime_operations_util'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def date_time_difference(body: InputDateTimeDifference = None):
    """
    DateTime - DateTime difference
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/DateTimeInfo',
    description=""" Retrieve useful date and time information, such as day of year, total seconds and ticks """,
    tags=['date_time_utilities', 'datetime_operations_util'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def date_time_info(body: InputDateTimeInfo = None):
    """
    DateTime - Get date and time information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/DecodeString',
    description=""" Decode a string encoded with Base64 encoding """,
    tags=['text_transformation', 'string_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def decode_string(body: DecodeStringPostRequest = None):
    """
    Text - Decode string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/EncodeString',
    description=""" Encode a string using Base64 encoding """,
    tags=['text_transformation', 'string_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def encode_string(body: InputString = None):
    """
    Text - Encode string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/FileToString',
    description=""" Convert a file to a Base64 string """,
    tags=['string_operations', 'text_transformation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def file_to_string(file: UploadFile):
    """
    Files - File to string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/FilterCollection',
    description=""" Filter a collection of strings by keyword """,
    tags=['collection_manipulation', 'collection_management_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def filter_collection(body: InputCollectionFilter = None):
    """
    Collections - Filter collection
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/FlipImage',
    description=""" Flip an image (horizontal or vertical) """,
    tags=['image_file_processing', 'advanced_image_handling'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def flip_image(file: UploadFile):
    """
    Files - Flip Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/FormatCurrency',
    description=""" Apply currency symbol to a numeric value """,
    tags=['currency_exchange_operations', 'financial_data_handling'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def format_currency(body: InputCurrencyFormat = None):
    """
    Currency - Format currency
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/FormatDateTime',
    description=""" Create a date/time string in a specific format """,
    tags=['date_time_utilities', 'datetime_operations_util'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def format_date_time(body: InputDateTimeFormat = None):
    """
    DateTime - Format date and time
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GenerateGuid',
    description=""" Generate a globally unique identifier """,
    tags=['identifier_and_hash_generation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def generate_guid(body: InputGenerateUniqueID = None):
    """
    Text - Generate GUID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GenerateHash',
    description=""" Generate a hash value from a string """,
    tags=['identifier_and_hash_generation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def generate_hash(body: InputGenerateHash = None):
    """
    Text - Generate hash
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/GenerateQRCode',
    description=""" Generate a QR code image """,
    tags=['qr_code_creation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def generate_q_r_code(body: InputQRCode = None):
    """
    Files - Generate QR code
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/JSONtoCSV',
    description=""" Convert a JSON array to CSV string """,
    tags=['data_format_conversion', 'collection_manipulation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def json_to_csv(body: InputJsonConversionCSV = None):
    """
    Data - JSON to CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/JSONtoHTML',
    description=""" Convert a JSON array to an HTML table """,
    tags=['data_format_conversion', 'collection_manipulation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def json_to_html(body: InputJsonConversionHTML = None):
    """
    Data - JSON to HTML Table
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/JSONtoXML',
    description=""" Convert a JSON object to an XML string """,
    tags=['data_format_conversion', 'collection_manipulation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def json_to_xml(body: InputJsonConversionXML = None):
    """
    Data - JSON to XML
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/JoinStrings',
    description=""" Join a collection of strings """,
    tags=['text_transformation', 'string_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def join_strings(body: InputJoinStrings = None):
    """
    Text - Join strings
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/MarketIndex',
    description=""" Get current and historical market index information """,
    tags=['financial_data_handling', 'finance_data_retrieval'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def market_index(body: InputMarketIndex = None):
    """
    Finance - Market index
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/QueryJSON',
    description=""" Query a JSON object using a JSONPath expression """,
    tags=['data_query_handling'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def query_json(body: InputDataQuery = None):
    """
    Data - Query JSON
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/QueryXML',
    description=""" Query an XML string using an XPath expression """,
    tags=['data_query_handling', 'data_format_conversion'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def query_xml(body: InputDataQuery = None):
    """
    Data - Query XML
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/RandomNumber',
    description=""" Generate a random number within a specified range """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def random_number(body: InputNumberRange = None):
    """
    Math - Random number
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/RedactString',
    description=""" Redact a strng containing sensitive content """,
    tags=['text_transformation', 'string_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def redact_string(body: InputRedactString = None):
    """
    Text - Redact string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/RemoveFromCollection',
    description=""" Remove an item from a collection """,
    tags=['collection_manipulation', 'collection_management_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def remove_from_collection(body: InputCollectionModify = None):
    """
    Collections - Remove from collection
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ReplaceString',
    description=""" Replace one value with another in a string """,
    tags=['text_transformation', 'string_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def replace_string(body: InputReplaceString = None):
    """
    Text - Replace string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ReplaceValuesInCollection',
    description=""" Replace whole or partial strings in a collection """,
    tags=['collection_manipulation', 'collection_management_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def replace_values_in_collection(body: InputCollectionReplace = None):
    """
    Collections - Replace values in collection
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ResizeImage',
    description=""" Resize an image """,
    tags=['image_file_processing', 'advanced_image_handling'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def resize_image(file: UploadFile):
    """
    Files - Resize Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/RotateImage',
    description=""" Rotate an image by specified number of degrees """,
    tags=['image_file_processing', 'advanced_image_handling'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def rotate_image(file: UploadFile):
    """
    Files - Rotate Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/RoundNumber',
    description=""" Round a numeric value up or down """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def round_number(body: InputCalculateNumber = None):
    """
    Math - Round number
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ShortenLink',
    description=""" Generate a simple, short URL from a complex URL """,
    tags=['text_transformation', 'url_encoding_decoding'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def shorten_link(body: ShortenLinkPostRequest = None):
    """
    Text - Shorten hyperlink
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/SortCollection',
    description=""" Sort a collection of strings """,
    tags=['collection_management_operations', 'collection_manipulation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def sort_collection(body: InputCollectionSort = None):
    """
    Collections - Sort collection
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/SpeechToText',
    description=""" Convert audio file to text (10MB limit) """,
    tags=['text_to_speech_processing', 'text_transformation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def speech_to_text(file: UploadFile):
    """
    Text - Speech to Text
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/SplitCollection',
    description=""" Split a collection of items by matching value or index """,
    tags=['collection_manipulation', 'collection_management_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def split_collection(body: InputCollectionSplit = None):
    """
    Collections - Split collection
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/SplitString',
    description=""" Split a string based upon one or more characters """,
    tags=[
        'collection_management_operations',
        'string_operations',
        'text_transformation',
    ],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def split_string(body: InputSplitString = None):
    """
    Text - Split string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/StandardDeviation',
    description=""" Calculate the standard deviation of two or more numbers """,
    tags=['math_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def standard_deviation(body: InputCalculateSeries = None):
    """
    Math - Calculate standard deviation
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/StockPrices',
    description=""" Get current and historical stock price information """,
    tags=['financial_data_handling', 'finance_data_retrieval'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def stock_prices(body: InputStockPrices = None):
    """
    Finance - Stock prices
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/StringToFile',
    description=""" Convert text string to file """,
    tags=['text_transformation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def string_to_file(body: InputStringToFile = None):
    """
    Text - String to File
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/TextToSpeech',
    description=""" Convert text to an audio file using AI-driven speech synthesis. """,
    tags=['text_to_speech_processing'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def text_to_speech(body: InputTextToSpeech = None):
    """
    Text - Text to Speech
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/TranslateString',
    description=""" Translate a string into a different language """,
    tags=['text_transformation', 'string_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def translate_string(body: InputTranslateString = None):
    """
    Text - Translate string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/TrimString',
    description=""" Trim leading or trailing whitespace from a string """,
    tags=['text_transformation', 'string_operations'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def trim_string(body: InputTrimString = None):
    """
    Text - Trim string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/URLDecode',
    description=""" Decode an encoded URL """,
    tags=['url_encoding_decoding', 'text_transformation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def url_decode(body: URLDecodePostRequest = None):
    """
    Text - Decode URL
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/URLEncode',
    description=""" Generate an encoded string from a complex hyperlink """,
    tags=['url_encoding_decoding', 'text_transformation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def url_encode(body: InputString = None):
    """
    Text - Encode URL
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ValidateEmail',
    description=""" Determine if an email address is valid """,
    tags=['email_address_validation'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def validate_email(body: ValidateEmailPostRequest = None):
    """
    Text - Validate email
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/VerifyHash',
    description=""" Verify a hashed value against the original source string """,
    tags=['identifier_and_hash_generation', 'hash_verification_utilities'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def verify_hash(body: InputVerifyHash = None):
    """
    Text - Verify hash
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/WatermarkImage',
    description=""" Add watermark text to an image """,
    tags=['image_file_processing', 'advanced_image_handling'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def watermark_image(file: UploadFile):
    """
    Files - Watermark Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/WorldTime',
    description=""" Convert date and time from one time zone to another """,
    tags=['date_time_utilities', 'datetime_operations_util'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def world_time(body: InputDateTimeConversion = None):
    """
    DateTime - Get world time
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/XMLtoJSON',
    description=""" Convert an XML string to a JSON object """,
    tags=['data_format_conversion', 'collection_manipulation', 'data_query_handling'],
    security=[
        APIKeyHeader(name="X-IBM-Client-Id"),
    ],
)
def xml_to_json(body: InputXmlConversionJSON = None):
    """
    Data - XML to JSON
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
