# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:49:18+00:00

from __future__ import annotations

from enum import Enum
from typing import Any as Any_aliased
from typing import List, Optional

from pydantic import BaseModel, Field, confloat


class Type(Enum):
    Minimum = 'Minimum'
    Maximum = 'Maximum'


class InputCalculateMinMax(BaseModel):
    input: List[float] = Field(..., description='Colllection of values to calculate')
    type: Type = Field(..., description='Minimum or Maximum')


class InputCalculateNumber(BaseModel):
    decimals: confloat(ge=0.0) = Field(
        ..., description='Round to number of decimal places'
    )
    input: float = Field(..., description='Numeric value to calculate')


class InputCalculateNumbers(BaseModel):
    decimals: confloat(ge=0.0) = Field(
        ..., description='Round to number of decimal places'
    )
    input: float = Field(..., description='Numeric value')
    value: float = Field(
        ..., description='Addend, subtrahend, factor, divisor or radicand'
    )


class InputCalculatePower(BaseModel):
    decimals: confloat(ge=0.0) = Field(
        ..., description='Round to number of decimal places'
    )
    input: float = Field(..., description='Number to raise')
    power: float = Field(..., description='Power')


class InputCalculateSeries(BaseModel):
    decimals: confloat(ge=0.0) = Field(
        ..., description='Round to number of decimal places'
    )
    input: List[float] = Field(..., description='Colllection of values to calculate')


class Alphacase(Enum):
    Upper = 'Upper'
    Lower = 'Lower'
    Title = 'Title'


class InputCaseConversion(BaseModel):
    alphacase: Alphacase = Field(..., description='Case of conversion result')
    input: str = Field(..., description='String containing the text to convert')


class InputCollectionConversion(BaseModel):
    input: List[str] = Field(
        ..., description='Collection containing strings to convert'
    )
    name: str = Field(..., description='Collection name')


class InputCollectionConversionXML(BaseModel):
    child: str = Field(..., description='Name of child XML node(s)')
    input: List[str] = Field(
        ..., description='Collection containing strings to convert'
    )
    root: str = Field(..., description='Name of root XML node')


class InputCollectionCount(BaseModel):
    input: List[str] = Field(..., description='Collection of items to count')


class Match(Enum):
    Any = 'Any'
    All = 'All'
    None_ = 'None'


class InputCollectionFilter(BaseModel):
    input: List[str] = Field(..., description='Collection of strings to filter')
    keywords: str = Field(
        ..., description='Keywords (separate multiple values with commas)'
    )
    match: Match = Field(..., description='Match type')


class InputCollectionModify(BaseModel):
    index: Optional[str] = Field(
        None,
        description='Index position for operation (leave blank to specify end of collection)',
    )
    input: List[str] = Field(
        ..., description='Collection of values or objects to modify'
    )
    item: Optional[str] = Field(
        None, description='Item (for multiple items, leave blank and use Items)'
    )
    items: Optional[List[str]] = Field(
        None,
        description='Items (Collection, for a single item leave blank and use Item)',
    )


class IgnoreCase(Enum):
    True_ = True
    False_ = False


class InputCollectionReplace(BaseModel):
    ignoreCase: IgnoreCase = Field(..., description='Ignore case')
    input: List[str] = Field(..., description='Collection of strings')
    match: str = Field(..., description='Match value')
    replacement: str = Field(..., description='Replacement value')


class Ignorecase(Enum):
    True_ = True
    False_ = False


class Trim(Enum):
    True_ = True
    False_ = False


class InputCollectionSearch(BaseModel):
    ignorecase: Optional[Ignorecase] = Field(
        None, description='Ignore case when performing comparison'
    )
    input: List[str] = Field(..., description='Collection of strings to search')
    match: str = Field(..., description='Text to match')
    trim: Optional[Trim] = Field(
        None, description='Trim white space from comparison string'
    )


class Type1(Enum):
    Integer = 'Integer'
    Decimal = 'Decimal'


class InputCollectionSearchNumeric(BaseModel):
    input: List[float] = Field(..., description='Collection of strings to search')
    match: float = Field(..., description='Number to match')
    type: Optional[Type1] = Field(
        'Integer', description='Type of number - integer or decimal'
    )


class Order(Enum):
    Ascending = 'Ascending'
    Descending = 'Descending'


class InputCollectionSort(BaseModel):
    input: List[str] = Field(..., description='Collection of strings to sort')
    order: Order = Field(..., description='Sort order')


class InputCollectionSplit(BaseModel):
    index: Optional[str] = Field(
        None, description='Index location to split (leave empty to use Match value)'
    )
    input: List[str] = Field(..., description='Collection of items to split')
    match: Optional[str] = Field(
        None,
        description='String to match (explicit, case-insensitive, leave empty to use Index)',
    )


class Source(Enum):
    Arcminute = 'Arcminute'
    Arcsecond = 'Arcsecond'
    Centiradian = 'Centiradian'
    Deciradian = 'Deciradian'
    Degree = 'Degree'
    Gradian = 'Gradian'
    Microdegree = 'Microdegree'
    Microradian = 'Microradian'
    Millidegree = 'Millidegree'
    Milliradian = 'Milliradian'
    Nanodegree = 'Nanodegree'
    Nanoradian = 'Nanoradian'
    Radian = 'Radian'
    Revolution = 'Revolution'


class Target(Enum):
    Arcminute = 'Arcminute'
    Arcsecond = 'Arcsecond'
    Centiradian = 'Centiradian'
    Deciradian = 'Deciradian'
    Degree = 'Degree'
    Gradian = 'Gradian'
    Microdegree = 'Microdegree'
    Microradian = 'Microradian'
    Millidegree = 'Millidegree'
    Milliradian = 'Milliradian'
    Nanodegree = 'Nanodegree'
    Nanoradian = 'Nanoradian'
    Radian = 'Radian'
    Revolution = 'Revolution'


class InputConvertAngle(BaseModel):
    input: float
    source: Source
    target: Target


class Source1(Enum):
    Acre = 'Acre'
    Hectare = 'Hectare'
    SquareCentimeter = 'SquareCentimeter'
    SquareDecimeter = 'SquareDecimeter'
    SquareFoot = 'SquareFoot'
    SquareInch = 'SquareInch'
    SquareKilometer = 'SquareKilometer'
    SquareMeter = 'SquareMeter'
    SquareMicrometer = 'SquareMicrometer'
    SquareMile = 'SquareMile'
    SquareMillimeter = 'SquareMillimeter'
    SquareYard = 'SquareYard'


class Target1(Enum):
    Acre = 'Acre'
    Hectare = 'Hectare'
    SquareCentimeter = 'SquareCentimeter'
    SquareDecimeter = 'SquareDecimeter'
    SquareFoot = 'SquareFoot'
    SquareInch = 'SquareInch'
    SquareKilometer = 'SquareKilometer'
    SquareMeter = 'SquareMeter'
    SquareMicrometer = 'SquareMicrometer'
    SquareMile = 'SquareMile'
    SquareMillimeter = 'SquareMillimeter'
    SquareYard = 'SquareYard'


class InputConvertArea(BaseModel):
    input: float
    source: Source1
    target: Target1


class Source2(Enum):
    Centimeter = 'Centimeter'
    Decimeter = 'Decimeter'
    Fathom = 'Fathom'
    Foot = 'Foot'
    Hectometer = 'Hectometer'
    Inch = 'Inch'
    Kilometer = 'Kilometer'
    LightYear = 'LightYear'
    Meter = 'Meter'
    Micrometer = 'Micrometer'
    Mile = 'Mile'
    Millimeter = 'Millimeter'
    Nanometer = 'Nanometer'
    NauticalMile = 'NauticalMile'
    Yard = 'Yard'


class Target2(Enum):
    Centimeter = 'Centimeter'
    Decimeter = 'Decimeter'
    Fathom = 'Fathom'
    Foot = 'Foot'
    Hectometer = 'Hectometer'
    Inch = 'Inch'
    Kilometer = 'Kilometer'
    LightYear = 'LightYear'
    Meter = 'Meter'
    Micrometer = 'Micrometer'
    Mile = 'Mile'
    Millimeter = 'Millimeter'
    Nanometer = 'Nanometer'
    NauticalMile = 'NauticalMile'
    Yard = 'Yard'


class InputConvertDistance(BaseModel):
    input: float
    source: Source2
    target: Target2


class Source3(Enum):
    Day = 'Day'
    Hour = 'Hour'
    Microsecond = 'Microsecond'
    Millisecond = 'Millisecond'
    Minute = 'Minute'
    Month = 'Month'
    Nanosecond = 'Nanosecond'
    Second = 'Second'
    Week = 'Week'
    Year = 'Year'


class Target3(Enum):
    Day = 'Day'
    Hour = 'Hour'
    Microsecond = 'Microsecond'
    Millisecond = 'Millisecond'
    Minute = 'Minute'
    Month = 'Month'
    Nanosecond = 'Nanosecond'
    Second = 'Second'
    Week = 'Week'
    Year = 'Year'


class InputConvertDuration(BaseModel):
    input: float
    source: Source3
    target: Target3


class Source4(Enum):
    BritishThermalUnit = 'BritishThermalUnit'
    Calorie = 'Calorie'
    ElectronVolt = 'ElectronVolt'
    FootPound = 'FootPound'
    GigawattHour = 'GigawattHour'
    Joule = 'Joule'
    Kilocalorie = 'Kilocalorie'
    Kilojoule = 'Kilojoule'
    KilowattHour = 'KilowattHour'
    Megajoule = 'Megajoule'
    MegawattHour = 'MegawattHour'
    TerawattHour = 'TerawattHour'
    Therm__EU_ = 'Therm (EU)'
    Therm__UK_ = 'Therm (UK)'
    Therm__US_ = 'Therm (US)'
    WattHour = 'WattHour'


class Target4(Enum):
    BritishThermalUnit = 'BritishThermalUnit'
    Calorie = 'Calorie'
    ElectronVolt = 'ElectronVolt'
    FootPound = 'FootPound'
    GigawattHour = 'GigawattHour'
    Joule = 'Joule'
    Kilocalorie = 'Kilocalorie'
    Kilojoule = 'Kilojoule'
    KilowattHour = 'KilowattHour'
    Megajoule = 'Megajoule'
    MegawattHour = 'MegawattHour'
    TerawattHour = 'TerawattHour'
    Therm__EU_ = 'Therm (EU)'
    Therm__UK_ = 'Therm (UK)'
    Therm__US_ = 'Therm (US)'
    WattHour = 'WattHour'


class InputConvertEnergy(BaseModel):
    input: float
    source: Source4
    target: Target4


class Source5(Enum):
    BritishThermalUnitPerHour = 'BritishThermalUnitPerHour'
    Decawatt = 'Decawatt'
    Deciwatt = 'Deciwatt'
    ElectricalHorsepower = 'ElectricalHorsepower'
    Femtowatt = 'Femtowatt'
    Gigawatt = 'Gigawatt'
    HydraulicHorsepower = 'HydraulicHorsepower'
    Kilowatt = 'Kilowatt'
    MechanicalHorsepower = 'MechanicalHorsepower'
    Megawatt = 'Megawatt'
    Microwatt = 'Microwatt'
    Milliwatt = 'Milliwatt'
    Nanowatt = 'Nanowatt'
    Petawatt = 'Petawatt'
    Picowatt = 'Picowatt'
    Terawatt = 'Terawatt'
    Watt = 'Watt'


class Target5(Enum):
    BritishThermalUnitPerHour = 'BritishThermalUnitPerHour'
    Decawatt = 'Decawatt'
    Deciwatt = 'Deciwatt'
    ElectricalHorsepower = 'ElectricalHorsepower'
    Femtowatt = 'Femtowatt'
    Gigawatt = 'Gigawatt'
    HydraulicHorsepower = 'HydraulicHorsepower'
    Kilowatt = 'Kilowatt'
    MechanicalHorsepower = 'MechanicalHorsepower'
    Megawatt = 'Megawatt'
    Microwatt = 'Microwatt'
    Milliwatt = 'Milliwatt'
    Nanowatt = 'Nanowatt'
    Petawatt = 'Petawatt'
    Picowatt = 'Picowatt'
    Terawatt = 'Terawatt'
    Watt = 'Watt'


class InputConvertPower(BaseModel):
    input: float
    source: Source5
    target: Target5


class Source6(Enum):
    CentimeterPerHour = 'CentimeterPerHour'
    CentimeterPerMinute = 'CentimeterPerMinute'
    CentimeterPerSecond = 'CentimeterPerSecond'
    DecimeterPerMinute = 'DecimeterPerMinute'
    DecimeterPerSecond = 'DecimeterPerSecond'
    FootPerHour = 'FootPerHour'
    FootPerMinute = 'FootPerMinute'
    FootPerSecond = 'FootPerSecond'
    InchPerHour = 'InchPerHour'
    InchPerMinute = 'InchPerMinute'
    InchPerSecond = 'InchPerSecond'
    KilometerPerHour = 'KilometerPerHour'
    KilometerPerMinute = 'KilometerPerMinute'
    KilometerPerSecond = 'KilometerPerSecond'
    Knot = 'Knot'
    MeterPerHour = 'MeterPerHour'
    MeterPerMinute = 'MeterPerMinute'
    MeterPerSecond = 'MeterPerSecond'
    MicrometerPerMinute = 'MicrometerPerMinute'
    MicrometerPerSecond = 'MicrometerPerSecond'
    MilePerHour = 'MilePerHour'
    MillimeterPerHour = 'MillimeterPerHour'
    MillimeterPerMinute = 'MillimeterPerMinute'
    MillimeterPerSecond = 'MillimeterPerSecond'
    NanometerPerMinute = 'NanometerPerMinute'
    NanometerPerSecond = 'NanometerPerSecond'
    YardPerHour = 'YardPerHour'
    YardPerMinute = 'YardPerMinute'
    YardPerSecond = 'YardPerSecond'


class Target6(Enum):
    CentimeterPerHour = 'CentimeterPerHour'
    CentimeterPerMinute = 'CentimeterPerMinute'
    CentimeterPerSecond = 'CentimeterPerSecond'
    DecimeterPerMinute = 'DecimeterPerMinute'
    DecimeterPerSecond = 'DecimeterPerSecond'
    FootPerHour = 'FootPerHour'
    FootPerMinute = 'FootPerMinute'
    FootPerSecond = 'FootPerSecond'
    InchPerHour = 'InchPerHour'
    InchPerMinute = 'InchPerMinute'
    InchPerSecond = 'InchPerSecond'
    KilometerPerHour = 'KilometerPerHour'
    KilometerPerMinute = 'KilometerPerMinute'
    KilometerPerSecond = 'KilometerPerSecond'
    Knot = 'Knot'
    MeterPerHour = 'MeterPerHour'
    MeterPerMinute = 'MeterPerMinute'
    MeterPerSecond = 'MeterPerSecond'
    MicrometerPerMinute = 'MicrometerPerMinute'
    MicrometerPerSecond = 'MicrometerPerSecond'
    MilePerHour = 'MilePerHour'
    MillimeterPerHour = 'MillimeterPerHour'
    MillimeterPerMinute = 'MillimeterPerMinute'
    MillimeterPerSecond = 'MillimeterPerSecond'
    NanometerPerMinute = 'NanometerPerMinute'
    NanometerPerSecond = 'NanometerPerSecond'
    YardPerHour = 'YardPerHour'
    YardPerMinute = 'YardPerMinute'
    YardPerSecond = 'YardPerSecond'


class InputConvertSpeed(BaseModel):
    input: float
    source: Source6
    target: Target6


class Source7(Enum):
    Celsius = 'Celsius'
    Fahrenheit = 'Fahrenheit'
    Newton = 'Newton'
    Kelvin = 'Kelvin'


class Target7(Enum):
    Celsius = 'Celsius'
    Fahrenheit = 'Fahrenheit'
    Newton = 'Newton'
    Kelvin = 'Kelvin'


class InputConvertTemperature(BaseModel):
    input: float
    source: Source7
    target: Target7


class Source8(Enum):
    Centiliter = 'Centiliter'
    CubicCentimeter = 'CubicCentimeter'
    CubicDecimeter = 'CubicDecimeter'
    CubicFoot = 'CubicFoot'
    CubicHectometer = 'CubicHectometer'
    CubicInch = 'CubicInch'
    CubicKilometer = 'CubicKilometer'
    CubicMeter = 'CubicMeter'
    CubicMillimeter = 'CubicMillimeter'
    CubicYard = 'CubicYard'
    Deciliter = 'Deciliter'
    ImperialBeerBarrel = 'ImperialBeerBarrel'
    ImperialGallon = 'ImperialGallon'
    ImperialOunce = 'ImperialOunce'
    ImperialPint = 'ImperialPint'
    Kiloliter = 'Kiloliter'
    Liter = 'Liter'
    Microliter = 'Microliter'
    Milliliter = 'Milliliter'
    Gallon = 'Gallon'
    Cup = 'Cup'
    Ounce = 'Ounce'
    Pint = 'Pint'
    Quart = 'Quart'
    Tablespoon = 'Tablespoon'
    Teaspoon = 'Teaspoon'


class Target8(Enum):
    Centiliter = 'Centiliter'
    CubicCentimeter = 'CubicCentimeter'
    CubicDecimeter = 'CubicDecimeter'
    CubicFoot = 'CubicFoot'
    CubicHectometer = 'CubicHectometer'
    CubicInch = 'CubicInch'
    CubicKilometer = 'CubicKilometer'
    CubicMeter = 'CubicMeter'
    CubicMillimeter = 'CubicMillimeter'
    CubicYard = 'CubicYard'
    Deciliter = 'Deciliter'
    ImperialBeerBarrel = 'ImperialBeerBarrel'
    ImperialGallon = 'ImperialGallon'
    ImperialOunce = 'ImperialOunce'
    ImperialPint = 'ImperialPint'
    Kiloliter = 'Kiloliter'
    Liter = 'Liter'
    Microliter = 'Microliter'
    Milliliter = 'Milliliter'
    Gallon = 'Gallon'
    Cup = 'Cup'
    Ounce = 'Ounce'
    Pint = 'Pint'
    Quart = 'Quart'
    Tablespoon = 'Tablespoon'
    Teaspoon = 'Teaspoon'


class InputConvertVolume(BaseModel):
    input: float
    source: Source8
    target: Target8


class Source9(Enum):
    Centigram = 'Centigram'
    Decagram = 'Decagram'
    Decigram = 'Decigram'
    Grain = 'Grain'
    Gram = 'Gram'
    Hectogram = 'Hectogram'
    Kilogram = 'Kilogram'
    Microgram = 'Microgram'
    Milligram = 'Milligram'
    Nanogram = 'Nanogram'
    Ounce = 'Ounce'
    Pound = 'Pound'
    Stone = 'Stone'
    Solar_Mass = 'Solar Mass'
    Earth_Mass = 'Earth Mass'
    Slug = 'Slug'
    Short_Ton = 'Short Ton'
    Long_Ton = 'Long Ton'
    Ton = 'Ton'
    Megaton = 'Megaton'
    Short_Hundredweight = 'Short Hundredweight'
    Long_Hundredweight = 'Long Hundredweight'


class Target9(Enum):
    Centigram = 'Centigram'
    Decagram = 'Decagram'
    Decigram = 'Decigram'
    Grain = 'Grain'
    Gram = 'Gram'
    Hectogram = 'Hectogram'
    Kilogram = 'Kilogram'
    Microgram = 'Microgram'
    Milligram = 'Milligram'
    Nanogram = 'Nanogram'
    Ounce = 'Ounce'
    Pound = 'Pound'
    Stone = 'Stone'
    Ton = 'Ton'


class InputConvertWeight(BaseModel):
    input: float
    source: Source9
    target: Target9


class InputCsvConversionJSON(BaseModel):
    header: bool = Field(..., description='Include header row')
    input: str = Field(..., description='CSV string')


class Source10(Enum):
    USD = 'USD'
    AUD = 'AUD'
    BGN = 'BGN'
    BRL = 'BRL'
    CAD = 'CAD'
    CHF = 'CHF'
    CNY = 'CNY'
    CZK = 'CZK'
    DKK = 'DKK'
    EUR = 'EUR'
    GBP = 'GBP'
    HKD = 'HKD'
    HRK = 'HRK'
    HUF = 'HUF'
    IDR = 'IDR'
    ILS = 'ILS'
    INR = 'INR'
    ISK = 'ISK'
    JPY = 'JPY'
    KRW = 'KRW'
    MXN = 'MXN'
    MYR = 'MYR'
    NOK = 'NOK'
    NZD = 'NZD'
    PHP = 'PHP'
    PLN = 'PLN'
    RON = 'RON'
    RUB = 'RUB'
    SGD = 'SGD'
    SEK = 'SEK'
    THB = 'THB'
    TRY = 'TRY'
    ZAR = 'ZAR'


class Target10(Enum):
    USD = 'USD'
    AUD = 'AUD'
    BGN = 'BGN'
    BRL = 'BRL'
    CAD = 'CAD'
    CHF = 'CHF'
    CNY = 'CNY'
    CZK = 'CZK'
    DKK = 'DKK'
    EUR = 'EUR'
    GBP = 'GBP'
    HKD = 'HKD'
    HRK = 'HRK'
    HUF = 'HUF'
    IDR = 'IDR'
    ILS = 'ILS'
    INR = 'INR'
    ISK = 'ISK'
    JPY = 'JPY'
    KRW = 'KRW'
    MXN = 'MXN'
    MYR = 'MYR'
    NOK = 'NOK'
    NZD = 'NZD'
    PHP = 'PHP'
    PLN = 'PLN'
    RON = 'RON'
    RUB = 'RUB'
    SGD = 'SGD'
    SEK = 'SEK'
    THB = 'THB'
    TRY = 'TRY'
    ZAR = 'ZAR'


class InputCurrencyConversion(BaseModel):
    input: float = Field(..., description='Amount to convert')
    source: Source10
    target: Target10


class InputCurrencyFormat(BaseModel):
    input: float = Field(..., description='Amount to format')
    target: Target10


class InputDataQuery(BaseModel):
    input: str = Field(..., description='XML or JSON string')
    query: str = Field(..., description='XPath or JSONPath query')


class Source11(Enum):
    GMT_Standard_Time____GMT__Greenwich_Mean_Time___Dublin__Edinburgh__Lisbon__London = 'GMT Standard Time - (GMT) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London'
    Greenwich_Standard_Time____GMT__Monrovia__Reykjavik = (
        'Greenwich Standard Time - (GMT) Monrovia, Reykjavik'
    )
    W__Europe_Standard_Time____GMT_01_00__Amsterdam__Berlin__Bern__Rome__Stockholm__Vienna = 'W. Europe Standard Time - (GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna'
    Central_Europe_Standard_Time____GMT_01_00__Belgrade__Bratislava__Budapest__Ljubljana__Prague = 'Central Europe Standard Time - (GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague'
    Central_European_Standard_Time____GMT_01_00__Sarajevo__Skopje__Warsaw__Zagreb = (
        'Central European Standard Time - (GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb'
    )
    W__Central_Africa_Standard_Time____GMT_01_00__West_Central_Africa = (
        'W. Central Africa Standard Time - (GMT+01:00) West Central Africa'
    )
    GTB_Standard_Time____GMT_02_00__Athens__Bucharest__Istanbul = (
        'GTB Standard Time - (GMT+02:00) Athens, Bucharest, Istanbul'
    )
    Middle_East_Standard_Time____GMT_02_00__Beirut = (
        'Middle East Standard Time - (GMT+02:00) Beirut'
    )
    Egypt_Standard_Time____GMT_02_00__Cairo = 'Egypt Standard Time - (GMT+02:00) Cairo'
    South_Africa_Standard_Time____GMT_02_00__Harare__Pretoria = (
        'South Africa Standard Time - (GMT+02:00) Harare, Pretoria'
    )
    FLE_Standard_Time____GMT_02_00__Helsinki__Kyiv__Riga__Sofia__Tallinn__Vilnius = (
        'FLE Standard Time - (GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius'
    )
    Israel_Standard_Time____GMT_02_00__Jerusalem = (
        'Israel Standard Time - (GMT+02:00) Jerusalem'
    )
    E__Europe_Standard_Time____GMT_02_00__Minsk = (
        'E. Europe Standard Time - (GMT+02:00) Minsk'
    )
    Namibia_Standard_Time____GMT_02_00__Windhoek = (
        'Namibia Standard Time - (GMT+02:00) Windhoek'
    )
    Arabic_Standard_Time____GMT_03_00__Baghdad = (
        'Arabic Standard Time - (GMT+03:00) Baghdad'
    )
    Arab_Standard_Time____GMT_03_00__Kuwait__Riyadh = (
        'Arab Standard Time - (GMT+03:00) Kuwait, Riyadh'
    )
    Russian_Standard_Time____GMT_03_00__Moscow__St__Petersburg__Volgograd = (
        'Russian Standard Time - (GMT+03:00) Moscow, St. Petersburg, Volgograd'
    )
    E__Africa_Standard_Time____GMT_03_00__Nairobi = (
        'E. Africa Standard Time - (GMT+03:00) Nairobi'
    )
    Georgian_Standard_Time____GMT_03_00__Tbilisi = (
        'Georgian Standard Time - (GMT+03:00) Tbilisi'
    )
    Iran_Standard_Time____GMT_03_30__Tehran = 'Iran Standard Time - (GMT+03:30) Tehran'
    Arabian_Standard_Time____GMT_04_00__Abu_Dhabi__Muscat = (
        'Arabian Standard Time - (GMT+04:00) Abu Dhabi, Muscat'
    )
    Azerbaijan_Standard_Time____GMT_04_00__Baku = (
        'Azerbaijan Standard Time - (GMT+04:00) Baku'
    )
    Mauritius_Standard_Time____GMT_04_00__Port_Louis = (
        'Mauritius Standard Time - (GMT+04:00) Port Louis'
    )
    Caucasus_Standard_Time____GMT_04_00__Yerevan = (
        'Caucasus Standard Time - (GMT+04:00) Yerevan'
    )
    Afghanistan_Standard_Time____GMT_04_30__Kabul = (
        'Afghanistan Standard Time - (GMT+04:30) Kabul'
    )
    Ekaterinburg_Standard_Time____GMT_05_00__Ekaterinburg = (
        'Ekaterinburg Standard Time - (GMT+05:00) Ekaterinburg'
    )
    Pakistan_Standard_Time____GMT_05_00__Islamabad__Karachi = (
        'Pakistan Standard Time - (GMT+05:00) Islamabad, Karachi'
    )
    West_Asia_Standard_Time____GMT_05_00__Tashkent = (
        'West Asia Standard Time - (GMT+05:00) Tashkent'
    )
    India_Standard_Time____GMT_05_30__Chennai__Kolkata__Mumbai__New_Delhi = (
        'India Standard Time - (GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi'
    )
    Sri_Lanka_Standard_Time____GMT_05_30__Sri_Jayawardenepura = (
        'Sri Lanka Standard Time - (GMT+05:30) Sri Jayawardenepura'
    )
    Nepal_Standard_Time____GMT_05_45__Kathmandu = (
        'Nepal Standard Time - (GMT+05:45) Kathmandu'
    )
    N__Central_Asia_Standard_Time____GMT_06_00__Almaty__Novosibirsk = (
        'N. Central Asia Standard Time - (GMT+06:00) Almaty, Novosibirsk'
    )
    Central_Asia_Standard_Time____GMT_06_00__Astana__Dhaka = (
        'Central Asia Standard Time - (GMT+06:00) Astana, Dhaka'
    )
    Myanmar_Standard_Time____GMT_06_30__Yangon__Rangoon_ = (
        'Myanmar Standard Time - (GMT+06:30) Yangon (Rangoon)'
    )
    SE_Asia_Standard_Time____GMT_07_00__Bangkok__Hanoi__Jakarta = (
        'SE Asia Standard Time - (GMT+07:00) Bangkok, Hanoi, Jakarta'
    )
    North_Asia_Standard_Time____GMT_07_00__Krasnoyarsk = (
        'North Asia Standard Time - (GMT+07:00) Krasnoyarsk'
    )
    China_Standard_Time____GMT_08_00__Beijing__Chongqing__Hong_Kong__Urumqi = (
        'China Standard Time - (GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi'
    )
    North_Asia_East_Standard_Time____GMT_08_00__Irkutsk__Ulaan_Bataar = (
        'North Asia East Standard Time - (GMT+08:00) Irkutsk, Ulaan Bataar'
    )
    Singapore_Standard_Time____GMT_08_00__Kuala_Lumpur__Singapore = (
        'Singapore Standard Time - (GMT+08:00) Kuala Lumpur, Singapore'
    )
    W__Australia_Standard_Time____GMT_08_00__Perth = (
        'W. Australia Standard Time - (GMT+08:00) Perth'
    )
    Taipei_Standard_Time____GMT_08_00__Taipei = (
        'Taipei Standard Time - (GMT+08:00) Taipei'
    )
    Tokyo_Standard_Time____GMT_09_00__Osaka__Sapporo__Tokyo = (
        'Tokyo Standard Time - (GMT+09:00) Osaka, Sapporo, Tokyo'
    )
    Korea_Standard_Time____GMT_09_00__Seoul = 'Korea Standard Time - (GMT+09:00) Seoul'
    Yakutsk_Standard_Time____GMT_09_00__Yakutsk = (
        'Yakutsk Standard Time - (GMT+09:00) Yakutsk'
    )
    Cen__Australia_Standard_Time____GMT_09_30__Adelaide = (
        'Cen. Australia Standard Time - (GMT+09:30) Adelaide'
    )
    AUS_Central_Standard_Time____GMT_09_30__Darwin = (
        'AUS Central Standard Time - (GMT+09:30) Darwin'
    )
    E__Australia_Standard_Time____GMT_10_00__Brisbane = (
        'E. Australia Standard Time - (GMT+10:00) Brisbane'
    )
    AUS_Eastern_Standard_Time____GMT_10_00__Canberra__Melbourne__Sydney = (
        'AUS Eastern Standard Time - (GMT+10:00) Canberra, Melbourne, Sydney'
    )
    West_Pacific_Standard_Time____GMT_10_00__Guam__Port_Moresby = (
        'West Pacific Standard Time - (GMT+10:00) Guam, Port Moresby'
    )
    Tasmania_Standard_Time____GMT_10_00__Hobart = (
        'Tasmania Standard Time - (GMT+10:00) Hobart'
    )
    Vladivostok_Standard_Time____GMT_10_00__Vladivostok = (
        'Vladivostok Standard Time - (GMT+10:00) Vladivostok'
    )
    Central_Pacific_Standard_Time____GMT_11_00__Magadan__Solomon_Is___New_Caledonia = 'Central Pacific Standard Time - (GMT+11:00) Magadan, Solomon Is., New Caledonia'
    New_Zealand_Standard_Time____GMT_12_00__Auckland__Wellington = (
        'New Zealand Standard Time - (GMT+12:00) Auckland, Wellington'
    )
    Fiji_Standard_Time____GMT_12_00__Fiji__Kamchatka__Marshall_Is_ = (
        'Fiji Standard Time - (GMT+12:00) Fiji, Kamchatka, Marshall Is.'
    )
    Tonga_Standard_Time____GMT_13_00__Nuku_alofa = (
        'Tonga Standard Time - (GMT+13:00) Nuku\'alofa'
    )
    Azores_Standard_Time____GMT_01_00__Azores = (
        'Azores Standard Time - (GMT-01:00) Azores'
    )
    Cape_Verde_Standard_Time____GMT_01_00__Cape_Verde_Is_ = (
        'Cape Verde Standard Time - (GMT-01:00) Cape Verde Is.'
    )
    Mid_Atlantic_Standard_Time____GMT_02_00__Mid_Atlantic = (
        'Mid-Atlantic Standard Time - (GMT-02:00) Mid-Atlantic'
    )
    E__South_America_Standard_Time____GMT_03_00__Brasilia = (
        'E. South America Standard Time - (GMT-03:00) Brasilia'
    )
    Argentina_Standard_Time____GMT_03_00__Buenos_Aires = (
        'Argentina Standard Time - (GMT-03:00) Buenos Aires'
    )
    SA_Eastern_Standard_Time____GMT_03_00__Georgetown = (
        'SA Eastern Standard Time - (GMT-03:00) Georgetown'
    )
    Greenland_Standard_Time____GMT_03_00__Greenland = (
        'Greenland Standard Time - (GMT-03:00) Greenland'
    )
    Montevideo_Standard_Time____GMT_03_00__Montevideo = (
        'Montevideo Standard Time - (GMT-03:00) Montevideo'
    )
    Newfoundland_Standard_Time____GMT_03_30__Newfoundland = (
        'Newfoundland Standard Time - (GMT-03:30) Newfoundland'
    )
    Atlantic_Standard_Time____GMT_04_00__Atlantic_Time__Canada_ = (
        'Atlantic Standard Time - (GMT-04:00) Atlantic Time (Canada)'
    )
    SA_Western_Standard_Time____GMT_04_00__La_Paz = (
        'SA Western Standard Time - (GMT-04:00) La Paz'
    )
    Central_Brazilian_Standard_Time____GMT_04_00__Manaus = (
        'Central Brazilian Standard Time - (GMT-04:00) Manaus'
    )
    Pacific_SA_Standard_Time____GMT_04_00__Santiago = (
        'Pacific SA Standard Time - (GMT-04:00) Santiago'
    )
    Venezuela_Standard_Time____GMT_04_30__Caracas = (
        'Venezuela Standard Time - (GMT-04:30) Caracas'
    )
    SA_Pacific_Standard_Time____GMT_05_00__Bogota__Lima__Quito__Rio_Branco = (
        'SA Pacific Standard Time - (GMT-05:00) Bogota, Lima, Quito, Rio Branco'
    )
    Eastern_Standard_Time____GMT_05_00__Eastern_Time__US___Canada_ = (
        'Eastern Standard Time - (GMT-05:00) Eastern Time (US & Canada)'
    )
    US_Eastern_Standard_Time____GMT_05_00__Indiana__East_ = (
        'US Eastern Standard Time - (GMT-05:00) Indiana (East)'
    )
    Central_America_Standard_Time____GMT_06_00__Central_America = (
        'Central America Standard Time - (GMT-06:00) Central America'
    )
    Central_Standard_Time____GMT_06_00__Central_Time__US___Canada_ = (
        'Central Standard Time - (GMT-06:00) Central Time (US & Canada)'
    )
    Central_Standard_Time__Mexico_____GMT_06_00__Guadalajara__Mexico_City__Monterrey = 'Central Standard Time (Mexico) - (GMT-06:00) Guadalajara, Mexico City, Monterrey'
    Canada_Central_Standard_Time____GMT_06_00__Saskatchewan = (
        'Canada Central Standard Time - (GMT-06:00) Saskatchewan'
    )
    US_Mountain_Standard_Time____GMT_07_00__Arizona = (
        'US Mountain Standard Time - (GMT-07:00) Arizona'
    )
    Mountain_Standard_Time__Mexico_____GMT_07_00__Chihuahua__La_Paz__Mazatlan = (
        'Mountain Standard Time (Mexico) - (GMT-07:00) Chihuahua, La Paz, Mazatlan'
    )
    Mountain_Standard_Time____GMT_07_00__Mountain_Time__US___Canada_ = (
        'Mountain Standard Time - (GMT-07:00) Mountain Time (US & Canada)'
    )
    Pacific_Standard_Time____GMT_08_00__Pacific_Time__US___Canada_ = (
        'Pacific Standard Time - (GMT-08:00) Pacific Time (US & Canada)'
    )
    Pacific_Standard_Time__Mexico_____GMT_08_00__Tijuana__Baja_California = (
        'Pacific Standard Time (Mexico) - (GMT-08:00) Tijuana, Baja California'
    )
    Alaskan_Standard_Time____GMT_09_00__Alaska = (
        'Alaskan Standard Time - (GMT-09:00) Alaska'
    )
    Hawaiian_Standard_Time____GMT_10_00__Hawaii = (
        'Hawaiian Standard Time - (GMT-10:00) Hawaii'
    )
    Samoa_Standard_Time____GMT_11_00__Midway_Island__Samoa = (
        'Samoa Standard Time - (GMT-11:00) Midway Island, Samoa'
    )
    Dateline_Standard_Time____GMT_12_00__International_Date_Line_West = (
        'Dateline Standard Time - (GMT-12:00) International Date Line West'
    )


class Target12(Enum):
    GMT_Standard_Time____GMT__Greenwich_Mean_Time___Dublin__Edinburgh__Lisbon__London = 'GMT Standard Time - (GMT) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London'
    Greenwich_Standard_Time____GMT__Monrovia__Reykjavik = (
        'Greenwich Standard Time - (GMT) Monrovia, Reykjavik'
    )
    W__Europe_Standard_Time____GMT_01_00__Amsterdam__Berlin__Bern__Rome__Stockholm__Vienna = 'W. Europe Standard Time - (GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna'
    Central_Europe_Standard_Time____GMT_01_00__Belgrade__Bratislava__Budapest__Ljubljana__Prague = 'Central Europe Standard Time - (GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague'
    Central_European_Standard_Time____GMT_01_00__Sarajevo__Skopje__Warsaw__Zagreb = (
        'Central European Standard Time - (GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb'
    )
    W__Central_Africa_Standard_Time____GMT_01_00__West_Central_Africa = (
        'W. Central Africa Standard Time - (GMT+01:00) West Central Africa'
    )
    GTB_Standard_Time____GMT_02_00__Athens__Bucharest__Istanbul = (
        'GTB Standard Time - (GMT+02:00) Athens, Bucharest, Istanbul'
    )
    Middle_East_Standard_Time____GMT_02_00__Beirut = (
        'Middle East Standard Time - (GMT+02:00) Beirut'
    )
    Egypt_Standard_Time____GMT_02_00__Cairo = 'Egypt Standard Time - (GMT+02:00) Cairo'
    South_Africa_Standard_Time____GMT_02_00__Harare__Pretoria = (
        'South Africa Standard Time - (GMT+02:00) Harare, Pretoria'
    )
    FLE_Standard_Time____GMT_02_00__Helsinki__Kyiv__Riga__Sofia__Tallinn__Vilnius = (
        'FLE Standard Time - (GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius'
    )
    Israel_Standard_Time____GMT_02_00__Jerusalem = (
        'Israel Standard Time - (GMT+02:00) Jerusalem'
    )
    E__Europe_Standard_Time____GMT_02_00__Minsk = (
        'E. Europe Standard Time - (GMT+02:00) Minsk'
    )
    Namibia_Standard_Time____GMT_02_00__Windhoek = (
        'Namibia Standard Time - (GMT+02:00) Windhoek'
    )
    Arabic_Standard_Time____GMT_03_00__Baghdad = (
        'Arabic Standard Time - (GMT+03:00) Baghdad'
    )
    Arab_Standard_Time____GMT_03_00__Kuwait__Riyadh = (
        'Arab Standard Time - (GMT+03:00) Kuwait, Riyadh'
    )
    Russian_Standard_Time____GMT_03_00__Moscow__St__Petersburg__Volgograd = (
        'Russian Standard Time - (GMT+03:00) Moscow, St. Petersburg, Volgograd'
    )
    E__Africa_Standard_Time____GMT_03_00__Nairobi = (
        'E. Africa Standard Time - (GMT+03:00) Nairobi'
    )
    Georgian_Standard_Time____GMT_03_00__Tbilisi = (
        'Georgian Standard Time - (GMT+03:00) Tbilisi'
    )
    Iran_Standard_Time____GMT_03_30__Tehran = 'Iran Standard Time - (GMT+03:30) Tehran'
    Arabian_Standard_Time____GMT_04_00__Abu_Dhabi__Muscat = (
        'Arabian Standard Time - (GMT+04:00) Abu Dhabi, Muscat'
    )
    Azerbaijan_Standard_Time____GMT_04_00__Baku = (
        'Azerbaijan Standard Time - (GMT+04:00) Baku'
    )
    Mauritius_Standard_Time____GMT_04_00__Port_Louis = (
        'Mauritius Standard Time - (GMT+04:00) Port Louis'
    )
    Caucasus_Standard_Time____GMT_04_00__Yerevan = (
        'Caucasus Standard Time - (GMT+04:00) Yerevan'
    )
    Afghanistan_Standard_Time____GMT_04_30__Kabul = (
        'Afghanistan Standard Time - (GMT+04:30) Kabul'
    )
    Ekaterinburg_Standard_Time____GMT_05_00__Ekaterinburg = (
        'Ekaterinburg Standard Time - (GMT+05:00) Ekaterinburg'
    )
    Pakistan_Standard_Time____GMT_05_00__Islamabad__Karachi = (
        'Pakistan Standard Time - (GMT+05:00) Islamabad, Karachi'
    )
    West_Asia_Standard_Time____GMT_05_00__Tashkent = (
        'West Asia Standard Time - (GMT+05:00) Tashkent'
    )
    India_Standard_Time____GMT_05_30__Chennai__Kolkata__Mumbai__New_Delhi = (
        'India Standard Time - (GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi'
    )
    Sri_Lanka_Standard_Time____GMT_05_30__Sri_Jayawardenepura = (
        'Sri Lanka Standard Time - (GMT+05:30) Sri Jayawardenepura'
    )
    Nepal_Standard_Time____GMT_05_45__Kathmandu = (
        'Nepal Standard Time - (GMT+05:45) Kathmandu'
    )
    N__Central_Asia_Standard_Time____GMT_06_00__Almaty__Novosibirsk = (
        'N. Central Asia Standard Time - (GMT+06:00) Almaty, Novosibirsk'
    )
    Central_Asia_Standard_Time____GMT_06_00__Astana__Dhaka = (
        'Central Asia Standard Time - (GMT+06:00) Astana, Dhaka'
    )
    Myanmar_Standard_Time____GMT_06_30__Yangon__Rangoon_ = (
        'Myanmar Standard Time - (GMT+06:30) Yangon (Rangoon)'
    )
    SE_Asia_Standard_Time____GMT_07_00__Bangkok__Hanoi__Jakarta = (
        'SE Asia Standard Time - (GMT+07:00) Bangkok, Hanoi, Jakarta'
    )
    North_Asia_Standard_Time____GMT_07_00__Krasnoyarsk = (
        'North Asia Standard Time - (GMT+07:00) Krasnoyarsk'
    )
    China_Standard_Time____GMT_08_00__Beijing__Chongqing__Hong_Kong__Urumqi = (
        'China Standard Time - (GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi'
    )
    North_Asia_East_Standard_Time____GMT_08_00__Irkutsk__Ulaan_Bataar = (
        'North Asia East Standard Time - (GMT+08:00) Irkutsk, Ulaan Bataar'
    )
    Singapore_Standard_Time____GMT_08_00__Kuala_Lumpur__Singapore = (
        'Singapore Standard Time - (GMT+08:00) Kuala Lumpur, Singapore'
    )
    W__Australia_Standard_Time____GMT_08_00__Perth = (
        'W. Australia Standard Time - (GMT+08:00) Perth'
    )
    Taipei_Standard_Time____GMT_08_00__Taipei = (
        'Taipei Standard Time - (GMT+08:00) Taipei'
    )
    Tokyo_Standard_Time____GMT_09_00__Osaka__Sapporo__Tokyo = (
        'Tokyo Standard Time - (GMT+09:00) Osaka, Sapporo, Tokyo'
    )
    Korea_Standard_Time____GMT_09_00__Seoul = 'Korea Standard Time - (GMT+09:00) Seoul'
    Yakutsk_Standard_Time____GMT_09_00__Yakutsk = (
        'Yakutsk Standard Time - (GMT+09:00) Yakutsk'
    )
    Cen__Australia_Standard_Time____GMT_09_30__Adelaide = (
        'Cen. Australia Standard Time - (GMT+09:30) Adelaide'
    )
    AUS_Central_Standard_Time____GMT_09_30__Darwin = (
        'AUS Central Standard Time - (GMT+09:30) Darwin'
    )
    E__Australia_Standard_Time____GMT_10_00__Brisbane = (
        'E. Australia Standard Time - (GMT+10:00) Brisbane'
    )
    AUS_Eastern_Standard_Time____GMT_10_00__Canberra__Melbourne__Sydney = (
        'AUS Eastern Standard Time - (GMT+10:00) Canberra, Melbourne, Sydney'
    )
    West_Pacific_Standard_Time____GMT_10_00__Guam__Port_Moresby = (
        'West Pacific Standard Time - (GMT+10:00) Guam, Port Moresby'
    )
    Tasmania_Standard_Time____GMT_10_00__Hobart = (
        'Tasmania Standard Time - (GMT+10:00) Hobart'
    )
    Vladivostok_Standard_Time____GMT_10_00__Vladivostok = (
        'Vladivostok Standard Time - (GMT+10:00) Vladivostok'
    )
    Central_Pacific_Standard_Time____GMT_11_00__Magadan__Solomon_Is___New_Caledonia = 'Central Pacific Standard Time - (GMT+11:00) Magadan, Solomon Is., New Caledonia'
    New_Zealand_Standard_Time____GMT_12_00__Auckland__Wellington = (
        'New Zealand Standard Time - (GMT+12:00) Auckland, Wellington'
    )
    Fiji_Standard_Time____GMT_12_00__Fiji__Kamchatka__Marshall_Is_ = (
        'Fiji Standard Time - (GMT+12:00) Fiji, Kamchatka, Marshall Is.'
    )
    Tonga_Standard_Time____GMT_13_00__Nuku_alofa = (
        'Tonga Standard Time - (GMT+13:00) Nuku\'alofa'
    )
    Azores_Standard_Time____GMT_01_00__Azores = (
        'Azores Standard Time - (GMT-01:00) Azores'
    )
    Cape_Verde_Standard_Time____GMT_01_00__Cape_Verde_Is_ = (
        'Cape Verde Standard Time - (GMT-01:00) Cape Verde Is.'
    )
    Mid_Atlantic_Standard_Time____GMT_02_00__Mid_Atlantic = (
        'Mid-Atlantic Standard Time - (GMT-02:00) Mid-Atlantic'
    )
    E__South_America_Standard_Time____GMT_03_00__Brasilia = (
        'E. South America Standard Time - (GMT-03:00) Brasilia'
    )
    Argentina_Standard_Time____GMT_03_00__Buenos_Aires = (
        'Argentina Standard Time - (GMT-03:00) Buenos Aires'
    )
    SA_Eastern_Standard_Time____GMT_03_00__Georgetown = (
        'SA Eastern Standard Time - (GMT-03:00) Georgetown'
    )
    Greenland_Standard_Time____GMT_03_00__Greenland = (
        'Greenland Standard Time - (GMT-03:00) Greenland'
    )
    Montevideo_Standard_Time____GMT_03_00__Montevideo = (
        'Montevideo Standard Time - (GMT-03:00) Montevideo'
    )
    Newfoundland_Standard_Time____GMT_03_30__Newfoundland = (
        'Newfoundland Standard Time - (GMT-03:30) Newfoundland'
    )
    Atlantic_Standard_Time____GMT_04_00__Atlantic_Time__Canada_ = (
        'Atlantic Standard Time - (GMT-04:00) Atlantic Time (Canada)'
    )
    SA_Western_Standard_Time____GMT_04_00__La_Paz = (
        'SA Western Standard Time - (GMT-04:00) La Paz'
    )
    Central_Brazilian_Standard_Time____GMT_04_00__Manaus = (
        'Central Brazilian Standard Time - (GMT-04:00) Manaus'
    )
    Pacific_SA_Standard_Time____GMT_04_00__Santiago = (
        'Pacific SA Standard Time - (GMT-04:00) Santiago'
    )
    Venezuela_Standard_Time____GMT_04_30__Caracas = (
        'Venezuela Standard Time - (GMT-04:30) Caracas'
    )
    SA_Pacific_Standard_Time____GMT_05_00__Bogota__Lima__Quito__Rio_Branco = (
        'SA Pacific Standard Time - (GMT-05:00) Bogota, Lima, Quito, Rio Branco'
    )
    Eastern_Standard_Time____GMT_05_00__Eastern_Time__US___Canada_ = (
        'Eastern Standard Time - (GMT-05:00) Eastern Time (US & Canada)'
    )
    US_Eastern_Standard_Time____GMT_05_00__Indiana__East_ = (
        'US Eastern Standard Time - (GMT-05:00) Indiana (East)'
    )
    Central_America_Standard_Time____GMT_06_00__Central_America = (
        'Central America Standard Time - (GMT-06:00) Central America'
    )
    Central_Standard_Time____GMT_06_00__Central_Time__US___Canada_ = (
        'Central Standard Time - (GMT-06:00) Central Time (US & Canada)'
    )
    Central_Standard_Time__Mexico_____GMT_06_00__Guadalajara__Mexico_City__Monterrey = 'Central Standard Time (Mexico) - (GMT-06:00) Guadalajara, Mexico City, Monterrey'
    Canada_Central_Standard_Time____GMT_06_00__Saskatchewan = (
        'Canada Central Standard Time - (GMT-06:00) Saskatchewan'
    )
    US_Mountain_Standard_Time____GMT_07_00__Arizona = (
        'US Mountain Standard Time - (GMT-07:00) Arizona'
    )
    Mountain_Standard_Time__Mexico_____GMT_07_00__Chihuahua__La_Paz__Mazatlan = (
        'Mountain Standard Time (Mexico) - (GMT-07:00) Chihuahua, La Paz, Mazatlan'
    )
    Mountain_Standard_Time____GMT_07_00__Mountain_Time__US___Canada_ = (
        'Mountain Standard Time - (GMT-07:00) Mountain Time (US & Canada)'
    )
    Pacific_Standard_Time____GMT_08_00__Pacific_Time__US___Canada_ = (
        'Pacific Standard Time - (GMT-08:00) Pacific Time (US & Canada)'
    )
    Pacific_Standard_Time__Mexico_____GMT_08_00__Tijuana__Baja_California = (
        'Pacific Standard Time (Mexico) - (GMT-08:00) Tijuana, Baja California'
    )
    Alaskan_Standard_Time____GMT_09_00__Alaska = (
        'Alaskan Standard Time - (GMT-09:00) Alaska'
    )
    Hawaiian_Standard_Time____GMT_10_00__Hawaii = (
        'Hawaiian Standard Time - (GMT-10:00) Hawaii'
    )
    Samoa_Standard_Time____GMT_11_00__Midway_Island__Samoa = (
        'Samoa Standard Time - (GMT-11:00) Midway Island, Samoa'
    )
    Dateline_Standard_Time____GMT_12_00__International_Date_Line_West = (
        'Dateline Standard Time - (GMT-12:00) International Date Line West'
    )


class InputDateTimeConversion(BaseModel):
    format: Optional[str] = Field(
        None, description="Display format (defaults to 'yyyy-MM-dd HH:mm:ss')"
    )
    input: str = Field(..., description='Source date and time')
    source: Source11
    target: Target12


class InputDateTimeDifference(BaseModel):
    dateTime1: str = Field(..., description='First date/time value')
    dateTime2: str = Field(..., description='Second date/time value')


class Culture(Enum):
    en_US = 'en-US'
    af_ZA = 'af-ZA'
    ar_AE = 'ar-AE'
    ar_BH = 'ar-BH'
    ar_DZ = 'ar-DZ'
    ar_EG = 'ar-EG'
    ar_IQ = 'ar-IQ'
    ar_JO = 'ar-JO'
    ar_KW = 'ar-KW'
    ar_LB = 'ar-LB'
    ar_LY = 'ar-LY'
    ar_MA = 'ar-MA'
    ar_OM = 'ar-OM'
    ar_QA = 'ar-QA'
    ar_SA = 'ar-SA'
    ar_SY = 'ar-SY'
    ar_TN = 'ar-TN'
    ar_YE = 'ar-YE'
    az_AZ = 'az-AZ'
    be_BY = 'be-BY'
    bg_BG = 'bg-BG'
    bs_BA = 'bs-BA'
    ca_ES = 'ca-ES'
    cs_CZ = 'cs-CZ'
    cy_GB = 'cy-GB'
    da_DK = 'da-DK'
    de_AT = 'de-AT'
    de_CH = 'de-CH'
    de_DE = 'de-DE'
    de_LI = 'de-LI'
    de_LU = 'de-LU'
    el_GR = 'el-GR'
    en_AU = 'en-AU'
    en_BZ = 'en-BZ'
    en_CA = 'en-CA'
    en_CB = 'en-CB'
    en_GB = 'en-GB'
    en_IE = 'en-IE'
    en_JM = 'en-JM'
    en_NZ = 'en-NZ'
    en_PH = 'en-PH'
    en_TT = 'en-TT'
    en_ZA = 'en-ZA'
    en_ZW = 'en-ZW'
    es_AR = 'es-AR'
    es_BO = 'es-BO'
    es_CL = 'es-CL'
    es_CO = 'es-CO'
    es_CR = 'es-CR'
    es_DO = 'es-DO'
    es_EC = 'es-EC'
    es_ES = 'es-ES'
    es_GT = 'es-GT'
    es_HN = 'es-HN'
    es_MX = 'es-MX'
    es_NI = 'es-NI'
    es_PA = 'es-PA'
    es_PE = 'es-PE'
    es_PR = 'es-PR'
    es_PY = 'es-PY'
    es_SV = 'es-SV'
    es_UY = 'es-UY'
    es_VE = 'es-VE'
    et_EE = 'et-EE'
    eu_ES = 'eu-ES'
    fa_IR = 'fa-IR'
    fi_FI = 'fi-FI'
    fo_FO = 'fo-FO'
    fr_BE = 'fr-BE'
    fr_CA = 'fr-CA'
    fr_CH = 'fr-CH'
    fr_FR = 'fr-FR'
    fr_LU = 'fr-LU'
    fr_MC = 'fr-MC'
    gl_ES = 'gl-ES'
    gu_IN = 'gu-IN'
    he_IL = 'he-IL'
    hi_IN = 'hi-IN'
    hr_BA = 'hr-BA'
    hr_HR = 'hr-HR'
    hu_HU = 'hu-HU'
    hy_AM = 'hy-AM'
    id_ID = 'id-ID'
    is_IS = 'is-IS'
    it_CH = 'it-CH'
    it_IT = 'it-IT'
    ja_JP = 'ja-JP'
    ka_GE = 'ka-GE'
    kk_KZ = 'kk-KZ'
    kn_IN = 'kn-IN'
    ko_KR = 'ko-KR'
    ky_KG = 'ky-KG'
    lt_LT = 'lt-LT'
    lv_LV = 'lv-LV'
    mi_NZ = 'mi-NZ'
    mn_MN = 'mn-MN'
    mr_IN = 'mr-IN'
    ms_BN = 'ms-BN'
    ms_MY = 'ms-MY'
    mt_MT = 'mt-MT'
    nl_BE = 'nl-BE'
    nl_NL = 'nl-NL'
    nn_NO = 'nn-NO'
    ns_ZA = 'ns-ZA'
    pa_IN = 'pa-IN'
    pl_PL = 'pl-PL'
    ps_AR = 'ps-AR'
    pt_BR = 'pt-BR'
    pt_PT = 'pt-PT'
    ro_RO = 'ro-RO'
    ru_RU = 'ru-RU'
    sa_IN = 'sa-IN'
    sk_SK = 'sk-SK'
    sl_SI = 'sl-SI'
    sq_AL = 'sq-AL'
    sr_BA = 'sr-BA'
    sr_SP = 'sr-SP'
    sv_FI = 'sv-FI'
    sv_SE = 'sv-SE'
    sw_KE = 'sw-KE'
    ta_IN = 'ta-IN'
    te_IN = 'te-IN'
    th_TH = 'th-TH'
    tl_PH = 'tl-PH'
    tn_ZA = 'tn-ZA'
    tr_TR = 'tr-TR'
    uk_UA = 'uk-UA'
    ur_PK = 'ur-PK'
    uz_UZ = 'uz-UZ'
    vi_VN = 'vi-VN'
    zh_CN = 'zh-CN'
    zh_HK = 'zh-HK'
    zh_MO = 'zh-MO'
    zh_SG = 'zh-SG'
    zh_TW = 'zh-TW'
    zu_ZA = 'zu-ZA'


class InputDateTimeFormat(BaseModel):
    culture: Culture = Field(..., description='Language culture')
    format: str = Field(..., description='Output format')
    input: str = Field(..., description='Source date and time')


class InputDateTimeInfo(BaseModel):
    culture: Culture = Field(..., description='Language culture')
    input: str = Field(..., description='Source date and time')


class Algorithm(Enum):
    MD5 = 'MD5'
    SHA1 = 'SHA1'
    SHA256 = 'SHA256'
    SHA384 = 'SHA384'
    SHA512 = 'SHA512'


class InputGenerateHash(BaseModel):
    algorithm: Algorithm = Field(..., description='Hash algorithm')
    input: str = Field(..., description='Hash source string')


class Uppercase(Enum):
    True_ = True
    False_ = False


class InputGenerateUniqueID(BaseModel):
    uppercase: Uppercase = Field(..., description='All uppercase alpha characters')


class Lower(Enum):
    True_ = True
    False_ = False


class InputJoinStrings(BaseModel):
    input: List[str] = Field(..., description='Collection of strings to be joined')
    lower: Lower = Field(..., description='Convert strings in collection to lowercase')
    separator: str = Field(..., description='Separator character')
    trim: Trim = Field(..., description='Trim strings in collection')


class InputJsonConversionCSV(BaseModel):
    header: bool = Field(..., description='Include header row')
    input: str = Field(..., description='JSON array object')
    omit: Optional[str] = Field(None, description='Columns to omit (comma separated)')
    order: Optional[str] = Field(None, description='Column order (comma separated)')


class InputJsonConversionHTML(BaseModel):
    alternate: Optional[str] = Field(None, description='Alternate header row markup')
    attributes: Optional[str] = Field(
        None, description='Optional table attributes (single quoted values)'
    )
    header: bool = Field(..., description='Include header row')
    input: str = Field(..., description='JSON array object')
    omit: Optional[str] = Field(None, description='Columns to omit (comma separated)')
    order: Optional[str] = Field(None, description='Column order (comma separated)')


class InputJsonConversionXML(BaseModel):
    input: str = Field(..., description='JSON array object')
    root: str = Field(..., description='Name of root node')


class Symbol(Enum):
    DJA_INDX__Dow_Jones_Composite_Average_ = 'DJA.INDX (Dow Jones Composite Average)'
    DJI_INDX__Dow_Jones_Industrial_Average_ = 'DJI.INDX (Dow Jones Industrial Average)'
    DJT_INDX__Dow_Jones_Transportation_ = 'DJT.INDX (Dow Jones Transportation)'
    DJUS_INDX__Dow_Jones_US_ = 'DJUS.INDX (Dow Jones US)'
    DXY_INDX__US_Dollar_Index_ = 'DXY.INDX (US Dollar Index)'
    GDOW_INDX__Global_Dow_USD_ = 'GDOW.INDX (Global Dow USD)'
    NY_INDX__NYSE_US_100_Index_ = 'NY.INDX (NYSE US 100 Index)'
    NYA_INDX__NYSE_Composite_ = 'NYA.INDX (NYSE Composite)'
    IXIC_INDX__NASDAQ_Composite_ = 'IXIC.INDX (NASDAQ Composite)'
    NDX_INDX__NASDAQ_100_ = 'NDX.INDX (NASDAQ 100)'
    GSPC_INDX__S_P_500_ = 'GSPC.INDX (S&P 500)'
    ES_INDX__S_P_500_Futures_ = 'ES.INDX (S&P 500 Futures)'
    MID_INDX__S_P_Midcap_400_ = 'MID.INDX (S&P Midcap 400)'
    GPTSE_INDX__S_P_TSX_Composite_Index__Canada__ = (
        'GPTSE.INDX (S&P TSX Composite Index [Canada])'
    )
    FTSE_INDX__FTSE_100_Index__UK__ = 'FTSE.INDX (FTSE 100 Index [UK])'
    CDAXX_INDX__DAX_Composite_Index__Germany__ = (
        'CDAXX.INDX (DAX Composite Index [Germany])'
    )
    GDAXI_INDX__DAX_Index__Germany__ = 'GDAXI.INDX (DAX Index [Germany])'
    HSCE_INDX__Hang_Seng_China_Enterprise__CEI__ = (
        'HSCE.INDX (Hang Seng China Enterprise (CEI))'
    )
    HSI_INDX__Hang_Seng_Index__Hong_Kong__ = 'HSI.INDX (Hang Seng Index [Hong Kong])'
    N100_INDX__EuroNext_100_ = 'N100.INDX (EuroNext 100)'
    N225_INDX__Nikkei_225_Index_ = 'N225.INDX (Nikkei 225 Index)'
    RTSI_INDX__RTSI_Index__Russia__ = 'RTSI.INDX (RTSI Index [Russia])'
    SSEC_INDX__Shanghai_Composite_ = 'SSEC.INDX (Shanghai Composite)'
    SSMI_INDX__Swiss_Market_Index_ = 'SSMI.INDX (Swiss Market Index)'


class InputMarketIndex(BaseModel):
    date: Optional[str] = Field(
        None, description='Date (yyyy-MM-dd, leave empty for last trading day)'
    )
    symbol: Symbol = Field(..., description='Market index')


class InputNumberRange(BaseModel):
    end: confloat(ge=0.0) = Field(..., description='End of range')
    start: confloat(ge=0.0) = Field(..., description='Start of range')


class Payload(Enum):
    Plain_Text__string_ = 'Plain Text (string)'
    Bitcoin_Payment__address_amount_label_message_ = (
        'Bitcoin Payment (address|amount|label|message)'
    )
    Bookmark__url_title_ = 'Bookmark (url|title)'
    Calendar_Event__subject_description_location_start_end_allDayEvent__true__or__false___format___universal__or__iCal___ = 'Calendar Event (subject|description|location|start|end|allDayEvent[\'true\' or \'false\']|format [\'universal\' or \'iCal\'])'
    Geolocation__latitude_longitude_ = 'Geolocation (latitude|longitude)'
    Mail__recipient_subject_message_ = 'Mail (recipient|subject|message)'
    Phone_Number__string_ = 'Phone Number (string)'
    SMS__number_message_ = 'SMS (number|message)'
    URL__string_ = 'URL (string)'
    WiFi__ssid_password_authenticationMode___WEP____WPA__or__WPA2___ = (
        'WiFi (ssid|password|authenticationMode [\'WEP\', \'WPA\' or \'WPA2\'])'
    )


class InputQRCode(BaseModel):
    input: str = Field(
        ..., description='Text value(s) (vertical bar delimited by type)'
    )
    payload: Payload = Field(..., description='Payload type')


class InputRedactString(BaseModel):
    regex: Optional[str] = Field(
        None, description='Regular expression pattern for matching strings'
    )
    source: str = Field(..., description='String containing the complete text')
    value: Optional[str] = Field(None, description='Individual string to redact')
    values: Optional[List[str]] = Field(
        None, description='Collection of strings to redact'
    )


class InputReplaceString(BaseModel):
    replacement: str = Field(..., description='Replacement text')
    source: str = Field(..., description='String containing the text to be replaced')
    value: str = Field(..., description='Text to replace')


class InputSplitString(BaseModel):
    characters: str = Field(
        ..., description='One or more characters that will be used to split the text'
    )
    input: str = Field(..., description='Text to split')


class Exchange(Enum):
    XNYS__New_York_Stock_Exchange_ = 'XNYS (New York Stock Exchange)'
    XNAS__NASDAQ_Stock_Exchange_ = 'XNAS (NASDAQ Stock Exchange)'
    XBRU__Euronext_Brussels_ = 'XBRU (Euronext Brussels)'
    XTSE__Toronto_Stock_Exchange_ = 'XTSE (Toronto Stock Exchange)'
    XCNQ__Candadian_Securities_Exchange_ = 'XCNQ (Candadian Securities Exchange)'
    XSHG__Shanghai_Stock_Exchange_ = 'XSHG (Shanghai Stock Exchange)'
    XCSE__Copenhagen_Stock_Exchange_ = 'XCSE (Copenhagen Stock Exchange)'
    XPAR__Euronext_Paris_ = 'XPAR (Euronext Paris)'
    XFRA__Deutsche_Borse_ = 'XFRA (Deutsche Borse)'
    XHKG__Hong_Kong_Stock_Exchange_ = 'XHKG (Hong Kong Stock Exchange)'
    XNSE__National_Stock_Exchange_India_ = 'XNSE (National Stock Exchange India)'
    XTAE__Tel_Aviv_Stock_Exchange_ = 'XTAE (Tel Aviv Stock Exchange)'
    XNGO__Nagoya_Stock_Exchange_ = 'XNGO (Nagoya Stock Exchange)'
    XFKA__Fukuoka_Stock_Exchange_ = 'XFKA (Fukuoka Stock Exchange)'
    XSAP__Sapporo_Stock_Exchange_ = 'XSAP (Sapporo Stock Exchange)'
    XMEX__Mexican_Stock_Exchange_ = 'XMEX (Mexican Stock Exchange)'
    XNZE__New_Zealand_Stock_Exchange_ = 'XNZE (New Zealand Stock Exchange)'
    XLIS__Euronext_Lisbon_ = 'XLIS (Euronext Lisbon)'
    MISX__Moscow_Stock_Exchange_ = 'MISX (Moscow Stock Exchange)'
    XSES__Singapore_Stock_Exchange_ = 'XSES (Singapore Stock Exchange)'
    XLON__London_Stock_Exchange_ = 'XLON (London Stock Exchange)'
    XASE__American_Stock_Exchange_ = 'XASE (American Stock Exchange)'
    XASX__Australia_Stock_Exchange_ = 'XASX (Australia Stock Exchange)'
    XDFM__Dubai_Financial_Market_ = 'XDFM (Dubai Financial Market)'
    XBKK__Stock_Exchange_of_Thailand_ = 'XBKK (Stock Exchange of Thailand)'
    XSWX__SIX_Swiss_Exchange_ = 'XSWX (SIX Swiss Exchange)'
    XSTO__Stockholm_Stock_Exchange_ = 'XSTO (Stockholm Stock Exchange)'
    BMEX__Bolsas_y_Mercados_Españoles_ = 'BMEX (Bolsas y Mercados Españoles)'
    XJSE__Johannesburg_Stock_Exchange_ = 'XJSE (Johannesburg Stock Exchange)'


class InputStockPrices(BaseModel):
    date: Optional[str] = Field(
        None, description='Date (yyyy-MM-dd, leave empty for latest)'
    )
    exchange: Optional[Exchange] = Field(None, description='Stock exchange')
    symbols: str = Field(
        ..., description='Stock ticker symbols (comma-separated, max 20)'
    )


class InputString(BaseModel):
    source: str = Field(..., description='String variable or text value')


class InputStringComparison(BaseModel):
    compare: str = Field(..., description='Comparison string')
    input: str = Field(..., description='Original string')
    lower: Lower = Field(
        ..., description='Convert strings to lowercase before comparison'
    )
    trim: Trim = Field(..., description='Trim strings before comparison')


class InputStringContains(BaseModel):
    find: str = Field(..., description='Text to match')
    input: str = Field(..., description='Text to search')
    lower: Lower = Field(..., description='Convert strings to lowercase')


class Extension(Enum):
    TXT = 'TXT'
    CSV = 'CSV'
    HTML = 'HTML'
    XML = 'XML'
    CSS = 'CSS'
    JSON = 'JSON'
    JS = 'JS'


class InputStringToFile(BaseModel):
    extension: Extension = Field(..., description='File extension')
    filename: str = Field(..., description='Name of file (without extension)')
    input: str = Field(..., description='Text string (body of file)')


class Type2(Enum):
    PlainText = 'PlainText'
    SSML = 'SSML'


class Voice(Enum):
    ar_EG__Hoda__Female_ = 'ar-EG, Hoda (Female)'
    ar_SA__Naayf__Male_ = 'ar-SA, Naayf (Male)'
    bg_BG__Ivan__Male_ = 'bg-BG, Ivan (Male)'
    ca_ES__Herena__Female_ = 'ca-ES, Herena (Female)'
    cs_CZ__Jakub__Male_ = 'cs-CZ, Jakub (Male)'
    da_DK__Helle__Female_ = 'da-DK, Helle (Female)'
    de_AT__Michael__Male_ = 'de-AT, Michael (Male)'
    de_CH__Karsten__Male_ = 'de-CH, Karsten (Male)'
    de_DE__Hedda__Female_ = 'de-DE, Hedda (Female)'
    de_DE__Stefan__Male_ = 'de-DE, Stefan (Male)'
    el_GR__Stefanos__Male_ = 'el-GR, Stefanos (Male)'
    en_AU__Catherine__Female_ = 'en-AU, Catherine (Female)'
    en_AU__Hayley__Female_ = 'en-AU, Hayley (Female)'
    en_CA__Heather__Female_ = 'en-CA, Heather (Female)'
    en_CA__Linda__Female_ = 'en-CA, Linda (Female)'
    en_GB__George__Male_ = 'en-GB, George (Male)'
    en_GB__Hazel__Female_ = 'en-GB, Hazel (Female)'
    en_GB__Susan__Female_ = 'en-GB, Susan (Female)'
    en_IE__Sean__Male_ = 'en-IE, Sean (Male)'
    en_IN__Heera__Female_ = 'en-IN, Heera (Female)'
    en_IN__Priya__Female_ = 'en-IN, Priya (Female)'
    en_IN__Ravi__Male_ = 'en-IN, Ravi (Male)'
    en_US__Aria__Female_ = 'en-US, Aria (Female)'
    en_US__Benjamin__Male_ = 'en-US, Benjamin (Male)'
    en_US__Guy__Male_ = 'en-US, Guy (Male)'
    en_US__Zira__Female_ = 'en-US, Zira (Female)'
    es_ES__Helena__Female_ = 'es-ES, Helena (Female)'
    es_ES__Laura__Female_ = 'es-ES, Laura (Female)'
    es_ES__Pablo__Male_ = 'es-ES, Pablo (Male)'
    es_MX__Hilda__Female_ = 'es-MX, Hilda (Female)'
    es_MX__Raul__Male_ = 'es-MX, Raul (Male)'
    fi_FI__Heidi__Female_ = 'fi-FI, Heidi (Female)'
    fr_CA__Caroline__Female_ = 'fr-CA, Caroline (Female)'
    fr_CA__Harmonie__Female_ = 'fr-CA, Harmonie (Female)'
    fr_CH__Guillaume__Male_ = 'fr-CH, Guillaume (Male)'
    fr_FR__Hortense__Female_ = 'fr-FR, Hortense (Female)'
    fr_FR__Julie__Female_ = 'fr-FR, Julie (Female)'
    fr_FR__Paul__Male_ = 'fr-FR, Paul (Male)'
    he_IL__Asaf__Male_ = 'he-IL, Asaf (Male)'
    hi_IN__Hemant__Male_ = 'hi-IN, Hemant (Male)'
    hi_IN__Kalpana__Female_ = 'hi-IN, Kalpana (Female)'
    hr_HR__Matej__Male_ = 'hr-HR, Matej (Male)'
    hu_HU__Szabolcs__Male_ = 'hu-HU, Szabolcs (Male)'
    id_ID__Andika__Male_ = 'id-ID, Andika (Male)'
    it_IT__Cosimo__Male_ = 'it-IT, Cosimo (Male)'
    it_IT__Lucia__Female_ = 'it-IT, Lucia (Female)'
    ja_JP__Ayumi__Female_ = 'ja-JP, Ayumi (Female)'
    ja_JP__Haruka__Female_ = 'ja-JP, Haruka (Female)'
    ja_JP__Ichiro__Male_ = 'ja-JP, Ichiro (Male)'
    ko_KR__Heami__Female_ = 'ko-KR, Heami (Female)'
    ms_MY__Rizwan__Male_ = 'ms-MY, Rizwan (Male)'
    nb_NO__Hulda__Female_ = 'nb-NO, Hulda (Female)'
    nl_NL__Hanna__Female_ = 'nl-NL, Hanna (Female)'
    pl_PL__Paulina__Female_ = 'pl-PL, Paulina (Female)'
    pt_BR__Daniel__Male_ = 'pt-BR, Daniel (Male)'
    pt_BR__Heloisa__Female_ = 'pt-BR, Heloisa (Female)'
    pt_PT__Helia__Female_ = 'pt-PT, Helia (Female)'
    ro_RO__Andrei__Male_ = 'ro-RO, Andrei (Male)'
    ru_RU__Ekaterina__Female_ = 'ru-RU, Ekaterina (Female)'
    ru_RU__Irina__Female_ = 'ru-RU, Irina (Female)'
    ru_RU__Pavel__Male_ = 'ru-RU, Pavel (Male)'
    sk_SK__Filip__Male_ = 'sk-SK, Filip (Male)'
    sl_SI__Lado__Male_ = 'sl-SI, Lado (Male)'
    sv_SE__Hedvig__Female_ = 'sv-SE, Hedvig (Female)'
    ta_IN__Valluvar__Male_ = 'ta-IN, Valluvar (Male)'
    te_IN__Chitra__Female_ = 'te-IN, Chitra (Female)'
    th_TH__Pattara__Male_ = 'th-TH, Pattara (Male)'
    tr_TR__Seda__Female_ = 'tr-TR, Seda (Female)'
    vi_VN__An__Male_ = 'vi-VN, An (Male)'
    zh_CN__Huihui__Female_ = 'zh-CN, Huihui (Female)'
    zh_CN__Kangkang__Male_ = 'zh-CN, Kangkang (Male)'
    zh_CN__Yaoyao__Female_ = 'zh-CN, Yaoyao (Female)'
    zh_HK__Danny__Male_ = 'zh-HK, Danny (Male)'
    zh_HK__Tracy__Female_ = 'zh-HK, Tracy (Female)'
    zh_TW__HanHan__Female_ = 'zh-TW, HanHan (Female)'
    zh_TW__Yating__Female_ = 'zh-TW, Yating (Female)'
    zh_TW__Zhiwei__Male_ = 'zh-TW, Zhiwei (Male)'


class InputTextToSpeech(BaseModel):
    text: str = Field(..., description='Text to convert (10,000 characters max)')
    type: Type2 = Field(..., description='Text or file type')
    voice: Voice = Field(
        ..., description='Voice locale (must match language of input text)'
    )


class Language(Enum):
    Arabic = 'Arabic'
    Chinese__Simplified_ = 'Chinese (Simplified)'
    Czech = 'Czech'
    Danish = 'Danish'
    Dutch = 'Dutch'
    English = 'English'
    Finnish = 'Finnish'
    French = 'French'
    German = 'German'
    Greek = 'Greek'
    Hindi = 'Hindi'
    Hungarian = 'Hungarian'
    Italian = 'Italian'
    Japanese = 'Japanese'
    Klingon = 'Klingon'
    Korean = 'Korean'
    Norweigan = 'Norweigan'
    Polish = 'Polish'
    Portuguese = 'Portuguese'
    Russian = 'Russian'
    Spanish = 'Spanish'
    Swedish = 'Swedish'
    Turkish = 'Turkish'
    Vietnamese = 'Vietnamese'
    Welsh = 'Welsh'


class InputTranslateString(BaseModel):
    input: str = Field(..., description='String containing the text to be translated')
    language: Language = Field(..., description='Translation language')


class Type3(Enum):
    Start = 'Start'
    End = 'End'
    Both = 'Both'


class InputTrimString(BaseModel):
    source: str = Field(..., description='String containing the text to be trimmed')
    type: Type3 = Field(..., description='Type of white space to remove')


class InputVerifyHash(BaseModel):
    algorithm: Algorithm = Field(..., description='Hash algorithm')
    hash: str = Field(..., description='Hashed result')
    input: str = Field(..., description='Original source string')


class InputXmlConversionJSON(BaseModel):
    input: str = Field(..., description='XML string')


class OutputBoolean(BaseModel):
    result: Optional[bool] = Field(None, description='Result')


class OutputCollectionNumber(BaseModel):
    item: Optional[float] = Field(None, description='First Value')
    items: Optional[List[float]] = Field(None, description='All Values')
    status: Optional[bool] = Field(None, description='Success')


class OutputCollectionResult(BaseModel):
    result: Optional[List[str]] = Field(None, description='Modified collection result')


class OutputCollectionString(BaseModel):
    item: Optional[str] = Field(None, description='First Value')
    items: Optional[List[str]] = Field(None, description='All Values')
    status: Optional[bool] = Field(None, description='Success')


class OutputDateDifference(BaseModel):
    days: Optional[float] = Field(None, description='Days')
    hours: Optional[float] = Field(None, description='Hours')
    milliseconds: Optional[float] = Field(None, description='Milliseconds')
    minutes: Optional[float] = Field(None, description='Minutes')
    months: Optional[float] = Field(None, description='Months')
    ticks: Optional[float] = Field(None, description='Ticks')
    totalDays: Optional[float] = Field(None, description='Total Days')
    totalHours: Optional[float] = Field(None, description='Total Hours')
    totalMilliseconds: Optional[float] = Field(None, description='Total Milliseconds')
    totalMinutes: Optional[float] = Field(None, description='Total Minutes')
    totalMonths: Optional[float] = Field(None, description='Total Months')
    totalSeconds: Optional[float] = Field(None, description='Total Seconds')
    totalYears: Optional[float] = Field(None, description='Total Years')
    years: Optional[float] = Field(None, description='Years')


class OutputDateInfo(BaseModel):
    DayOfWeek: Optional[float] = Field(None, description='DayOfWeek')
    DayOfYear: Optional[float] = Field(None, description='DayOfYear')
    MinutesInDay: Optional[float] = Field(None, description='MinutesInDay')
    SecondsInDay: Optional[float] = Field(None, description='SecondsInDay')
    Ticks: Optional[float] = Field(None, description='Ticks')
    WeekOfYear: Optional[float] = Field(None, description='WeekOfYear')


class OutputFileByte(BaseModel):
    result: Optional[str] = Field(None, description='Result')


class OutputMarketIndex(BaseModel):
    adj_close: Optional[float] = Field(None, description='Adjusted close value')
    adj_high: Optional[float] = Field(None, description='Adjusted high value')
    adj_low: Optional[float] = Field(None, description='Adjusted low value')
    adj_open: Optional[float] = Field(None, description='Adjusted open value')
    adj_volume: Optional[float] = Field(None, description='Adjusted trading volume')
    close: Optional[float] = Field(None, description='Close value')
    date: Optional[str] = Field(None, description='Date')
    exchange: Optional[str] = Field(None, description='Market exchange')
    high: Optional[float] = Field(None, description='High value')
    low: Optional[float] = Field(None, description='Low value')
    open: Optional[float] = Field(None, description='Open value')
    symbol: Optional[str] = Field(None, description='Index symbol')
    volume: Optional[float] = Field(None, description='Trading volume')


class OutputMultiCollection(BaseModel):
    result1: Optional[List[str]] = Field(None, description='First collection result')
    result2: Optional[List[str]] = Field(None, description='Second collection result')


class OutputNumber(BaseModel):
    result: Optional[float] = Field(None, description='Result')


class ResultItem(BaseModel):
    close: Optional[float] = Field(None, description='Close')
    date: Optional[str] = Field(None, description='Date')
    exchange: Optional[str] = Field(None, description='Stock exchange')
    high: Optional[float] = Field(None, description='High')
    low: Optional[float] = Field(None, description='Low')
    open: Optional[float] = Field(None, description='Open')
    symbol: Optional[str] = Field(None, description='Ticker symbol')
    volume: Optional[float] = Field(None, description='Volume')


class OutputStockPrice(BaseModel):
    result: Optional[List[ResultItem]] = Field(
        None, description='Stock price information'
    )


class OutputString(BaseModel):
    result: Optional[str] = Field(None, description='Result')


class OutputStringArray(BaseModel):
    data: Optional[List[str]] = Field(None, description='data')


class Format(Enum):
    PNG = 'PNG'
    JPG = 'JPG'
    GIF = 'GIF'
    BMP = 'BMP'
    TIF = 'TIF'


class ConvertImagePostRequest(BaseModel):
    file: bytes = Field(..., description='Source image file')
    format: Format = Field(..., description='Output file format')


class Position(Enum):
    TopLeft = 'TopLeft'
    TopCenter = 'TopCenter'
    TopRight = 'TopRight'
    MiddleLeft = 'MiddleLeft'
    MiddleCenter = 'MiddleCenter'
    MiddleRight = 'MiddleRight'
    BottomLeft = 'BottomLeft'
    BottomCenter = 'BottomCenter'
    BottomRight = 'BottomRight'


class CropImagePostRequest(BaseModel):
    Height: float = Field(..., description='Height (Y-axis down, negative to reverse)')
    Width: float = Field(..., description='Width (X-axis right, negative to reverse)')
    file: bytes = Field(..., description='Source image file')
    position: Position = Field(
        ...,
        description='Crop start position (use negative values to reverse crop area)',
    )


class DecodeStringPostRequest(BaseModel):
    source: str = Field(..., description='Encoded string variable or text value')


class FileToStringPostRequest(BaseModel):
    file: bytes = Field(..., description='Source file (10MB limit)')


class Orientation(Enum):
    Horizontal = 'Horizontal'
    Vertical = 'Vertical'


class FlipImagePostRequest(BaseModel):
    file: bytes = Field(..., description='Source image file')
    orientation: Orientation = Field(..., description='Horizontal or Vertical')


class Algorithm2(Enum):
    Bicubic__default_ = 'Bicubic (default)'
    Bilinear = 'Bilinear'
    Cubic__Box_ = 'Cubic (Box)'
    Cubic__Catmull_Rom_ = 'Cubic (Catmull-Rom)'
    Cubic__Hermite_ = 'Cubic (Hermite)'
    Cubic__Spline_ = 'Cubic (Spline)'
    Nearest_Neighbor = 'Nearest Neighbor'
    Sinc__Lanczos2_ = 'Sinc (Lanczos2)'
    Sinc__Lanczos3_ = 'Sinc (Lanczos3)'
    Sinc__Lanczos5_ = 'Sinc (Lanczos5)'
    Sinc__Lanczos8_ = 'Sinc (Lanczos8)'
    Robidoux = 'Robidoux'
    Robidoux_Sharp = 'Robidoux Sharp'


class Units(Enum):
    Pixels = 'Pixels'
    Percent = 'Percent'


class ResizeImagePostRequest(BaseModel):
    algorithm: Algorithm2 = Field(
        ..., description='Optimize output quality of the target image'
    )
    file: bytes = Field(..., description='Source image file')
    height: Optional[float] = Field(
        None, description='Image height (pixels or percent)'
    )
    units: Units = Field(..., description='Image adjustment units')
    width: Optional[float] = Field(None, description='Image width (pixels or percent)')


class RotateImagePostRequest(BaseModel):
    degrees: str = Field(..., description='Number of degrees')
    file: bytes = Field(..., description='Source image file')


class ShortenLinkPostRequest(BaseModel):
    source: str = Field(..., description='String variable or text value')


class Language1(Enum):
    Arabic__Bahrain_ = 'Arabic (Bahrain)'
    Arabic__Egypt_ = 'Arabic (Egypt)'
    Arabic__Iraq_ = 'Arabic (Iraq)'
    Arabic__Jordan_ = 'Arabic (Jordan)'
    Arabic__Kuwait_ = 'Arabic (Kuwait)'
    Arabic__Lebanon_ = 'Arabic (Lebanon)'
    Arabic__Oman_ = 'Arabic (Oman)'
    Arabic__Qatar_ = 'Arabic (Qatar)'
    Arabic__Saudi_Arabia_ = 'Arabic (Saudi Arabia)'
    Arabic__Syria_ = 'Arabic (Syria)'
    Arabic__United_Arab_Emirates_ = 'Arabic (United Arab Emirates)'
    Bulgarian__Bulgaria_ = 'Bulgarian (Bulgaria)'
    Catalan__Spain_ = 'Catalan (Spain)'
    Chinese__Cantonese__Traditional_ = 'Chinese (Cantonese, Traditional)'
    Chinese__Mandarin__Simplified_ = 'Chinese (Mandarin, Simplified)'
    Chinese__Taiwanese_Mandarin_ = 'Chinese (Taiwanese Mandarin)'
    Croatian__Croatia_ = 'Croatian (Croatia)'
    Czech__Czech_Republic_ = 'Czech (Czech Republic)'
    Danish__Denmark_ = 'Danish (Denmark)'
    Dutch__Netherlands_ = 'Dutch (Netherlands)'
    English__Australia_ = 'English (Australia)'
    English__Canada_ = 'English (Canada)'
    English__Hong_Kong_ = 'English (Hong Kong)'
    English__India_ = 'English (India)'
    English__Ireland_ = 'English (Ireland)'
    English__New_Zealand_ = 'English (New Zealand)'
    English__Philippines_ = 'English (Philippines)'
    English__Singapore_ = 'English (Singapore)'
    English__South_Africa_ = 'English (South Africa)'
    English__United_Kingdom_ = 'English (United Kingdom)'
    English__United_States_ = 'English (United States)'
    Estonian_Estonia_ = 'Estonian(Estonia)'
    Finnish__Finland_ = 'Finnish (Finland)'
    French__Canada_ = 'French (Canada)'
    French__France_ = 'French (France)'
    German__Germany_ = 'German (Germany)'
    Greek__Greece_ = 'Greek (Greece)'
    Gujarati__Indian_ = 'Gujarati (Indian)'
    Hindi__India_ = 'Hindi (India)'
    Hungarian__Hungary_ = 'Hungarian (Hungary)'
    Irish_Ireland_ = 'Irish(Ireland)'
    Italian__Italy_ = 'Italian (Italy)'
    Japanese__Japan_ = 'Japanese (Japan)'
    Korean__Korea_ = 'Korean (Korea)'
    Latvian__Latvia_ = 'Latvian (Latvia)'
    Lithuanian__Lithuania_ = 'Lithuanian (Lithuania)'
    Maltese_Malta_ = 'Maltese(Malta)'
    Marathi__India_ = 'Marathi (India)'
    Norwegian__Norway_ = 'Norwegian (Norway)'
    Polish__Poland_ = 'Polish (Poland)'
    Portuguese__Brazil_ = 'Portuguese (Brazil)'
    Portuguese__Portugal_ = 'Portuguese (Portugal)'
    Romanian__Romania_ = 'Romanian (Romania)'
    Russian__Russia_ = 'Russian (Russia)'
    Slovak__Slovakia_ = 'Slovak (Slovakia)'
    Slovenian__Slovenia_ = 'Slovenian (Slovenia)'
    Spanish__Argentina_ = 'Spanish (Argentina)'
    Spanish__Bolivia_ = 'Spanish (Bolivia)'
    Spanish__Chile_ = 'Spanish (Chile)'
    Spanish__Colombia_ = 'Spanish (Colombia)'
    Spanish__Costa_Rica_ = 'Spanish (Costa Rica)'
    Spanish__Cuba_ = 'Spanish (Cuba)'
    Spanish__Dominican_Republic_ = 'Spanish (Dominican Republic)'
    Spanish__Ecuador_ = 'Spanish (Ecuador)'
    Spanish__El_Salvador_ = 'Spanish (El Salvador)'
    Spanish__Guatemala_ = 'Spanish (Guatemala)'
    Spanish__Honduras_ = 'Spanish (Honduras)'
    Spanish__Mexico_ = 'Spanish (Mexico)'
    Spanish__Nicaragua_ = 'Spanish (Nicaragua)'
    Spanish__Panama_ = 'Spanish (Panama)'
    Spanish__Paraguay_ = 'Spanish (Paraguay)'
    Spanish__Peru_ = 'Spanish (Peru)'
    Spanish__Puerto_Rico_ = 'Spanish (Puerto Rico)'
    Spanish__Spain_ = 'Spanish (Spain)'
    Spanish__Uruguay_ = 'Spanish (Uruguay)'
    Spanish__USA_ = 'Spanish (USA)'
    Spanish__Venezuela_ = 'Spanish (Venezuela)'
    Swedish__Sweden_ = 'Swedish (Sweden)'
    Tamil__India_ = 'Tamil (India)'
    Telugu__India_ = 'Telugu (India)'
    Thai__Thailand_ = 'Thai (Thailand)'
    Turkish__Turkey_ = 'Turkish (Turkey)'


class SpeechToTextPostRequest(BaseModel):
    file: bytes = Field(..., description='Source audio file (WAV, MP3, AAC, M4A)')
    language: Language1 = Field(..., description='Language of audio input')


class URLDecodePostRequest(BaseModel):
    source: str = Field(..., description='Encoded string variable or text value')


class ValidateEmailPostRequest(BaseModel):
    source: str = Field(..., description='String variable or text value')


class Font(Enum):
    Arial = 'Arial'
    Arial_Black = 'Arial Black'
    Arial_Narrow = 'Arial Narrow'
    Book_Antiqua = 'Book Antiqua'
    Britannic_Bold = 'Britannic Bold'
    Brush_Script_MT = 'Brush Script MT'
    Calisto_MT = 'Calisto MT'
    Century_Gothic = 'Century Gothic'
    Century_Schoolbook = 'Century Schoolbook'
    Colonna_MT = 'Colonna MT'
    Comic_Sans_MS = 'Comic Sans MS'
    Cooper_Black = 'Cooper Black'
    Copperplate_Gothic_Bold = 'Copperplate Gothic Bold'
    Copperplate_Gothic_Light = 'Copperplate Gothic Light'
    Courier_New = 'Courier New'
    Edwardian_Script_ITC = 'Edwardian Script ITC'
    Engravers_MT = 'Engravers MT'
    Franklin_Gothic_Demi = 'Franklin Gothic Demi'
    Franklin_Gothic_Heavy = 'Franklin Gothic Heavy'
    Franklin_Gothic_Medium = 'Franklin Gothic Medium'
    Garamond = 'Garamond'
    Georgia = 'Georgia'
    Gill_Sans_MT = 'Gill Sans MT'
    Gill_Sans_MT_Condensed = 'Gill Sans MT Condensed'
    Gill_Sans_Ultra_Bold = 'Gill Sans Ultra Bold'
    Gill_Sans_Ultra_Bold_Condensed = 'Gill Sans Ultra Bold Condensed'
    Goudy_Old_Style = 'Goudy Old Style'
    Haettenschweiler = 'Haettenschweiler'
    Holidays_MT = 'Holidays MT'
    Impact = 'Impact'
    Lucida_Calligraphy = 'Lucida Calligraphy'
    Lucida_Console = 'Lucida Console'
    Lucida_Handwriting = 'Lucida Handwriting'
    Lucida_Sans_Typewriter = 'Lucida Sans Typewriter'
    Lucida_Sans_Unicode = 'Lucida Sans Unicode'
    Marlett = 'Marlett'
    Microsoft_Sans_Serif = 'Microsoft Sans Serif'
    MS_Outlook = 'MS Outlook'
    Palace_Script_MT = 'Palace Script MT'
    Palatino_Linotype = 'Palatino Linotype'
    Papyrus = 'Papyrus'
    Playbill = 'Playbill'
    Rockwell = 'Rockwell'
    Rockwell_Condensed = 'Rockwell Condensed'
    Rockwell_Extra_Bold = 'Rockwell Extra Bold'
    Script_MT_Bold = 'Script MT Bold'
    Stencil = 'Stencil'
    Symbol = 'Symbol'
    Tahoma = 'Tahoma'
    Times_New_Roman = 'Times New Roman'
    Trebuchet_MS = 'Trebuchet MS'
    Verdana = 'Verdana'
    Vivaldi = 'Vivaldi'
    Webdings = 'Webdings'
    Wingdings_1 = 'Wingdings 1'
    Wingdings_2 = 'Wingdings 2'
    Wingdings_3 = 'Wingdings 3'


class Horizontal(Enum):
    Left = 'Left'
    Center = 'Center'
    Right = 'Right'


class Vertical(Enum):
    Top = 'Top'
    Center = 'Center'
    Bottom = 'Bottom'


class WatermarkImagePostRequest(BaseModel):
    color: str = Field(..., description='Text color hex value')
    file: bytes = Field(..., description='Source image file')
    font: Font = Field(..., description='Text font')
    horizontal: Horizontal = Field(..., description='Horizontal alignment')
    size: float = Field(..., description='Font size (points)')
    text: str = Field(..., description='Watermark text')
    vertical: Vertical = Field(..., description='Vertical alignment')
